"""
generate_api_v1.py — emit the api_v1.* wrapper schema from dbt's manifest.

Reads target/manifest.json (produced by `dbt parse`), filters to models under
models/marts/api/, and writes one SQL migration that creates a view per model
in api_v1.<name without mart_ prefix>, with column COMMENT ON COLUMN
statements sourced from each model's schema.yml descriptions.

Output is idempotent — re-applying the migration is a no-op. New runs of this
generator overwrite the same file; the migration runner re-applies on every
`npm run migrate` (state-less by design — see atlas-data/ingest/scripts/migrate.ts).

Tracks the previous-generation view list in a state JSON file. When a model
disappears from models/marts/api/, the next generation emits
DROP VIEW IF EXISTS for it before the recreates — see PLAN-004 [Q17].

Usage:
    python generate_api_v1.py \\
        --manifest target/manifest.json \\
        --models-dir-prefix models/marts/api/ \\
        --state api_v1_state.json \\
        --out ../migrations/070_api_v1_generated.sql

See the PLAN for the full design rationale:
website/docs/ai-developer/plans/active/PLAN-004-postgrest-api-v1-wrapper.md
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


# --- The shape of the data we extract from manifest.json -------------------


@dataclass(frozen=True)
class WrapperColumn:
    name: str
    description: str  # may be empty string


@dataclass(frozen=True)
class WrapperView:
    """One api_v1.<view_name> wrapper. The underlying is marts.<source_relation>."""

    view_name: str  # e.g. "indicator_summary"
    source_schema: str  # e.g. "marts"
    source_relation: str  # e.g. "mart_indicator_summary"
    columns: tuple[WrapperColumn, ...]
    # The model's own description, emitted as COMMENT ON VIEW.
    #
    # This is how a published view carries its own documentation to consumers:
    # PostgREST surfaces relation comments in its OpenAPI output, so an external
    # caller reading /rest/v1/ sees it without knowing meta_sources exists.
    #
    # 🔴 That matters legally, not only ergonomically. NLOD 2.0 requires
    # attribution to accompany redistributed data, and a consumer querying
    # api_v1.brreg_enhet has no reason to go and look up a separate catalogue
    # row. Putting the attribution in the view comment costs nothing per row —
    # unlike a repeated column across 1.17M records — and travels with the
    # endpoint.
    description: str = ""


# --- Manifest extraction ---------------------------------------------------


def _strip_mart_prefix(name: str) -> str:
    """Drop the leading 'mart_' so api_v1 names are unprefixed (PLAN-004 [Q2])."""
    return name[len("mart_") :] if name.startswith("mart_") else name


def extract_wrappers(
    manifest: dict, models_dir_prefix: str = "models/marts/api/"
) -> list[WrapperView]:
    """Walk manifest.json; return one WrapperView per dbt model under api/."""
    wrappers: list[WrapperView] = []
    for node in manifest.get("nodes", {}).values():
        if node.get("resource_type") != "model":
            continue
        if not node.get("original_file_path", "").startswith(models_dir_prefix):
            continue
        cols = tuple(
            WrapperColumn(name=c["name"], description=(c.get("description") or "").strip())
            for c in node["columns"].values()
        )
        wrappers.append(
            WrapperView(
                view_name=_strip_mart_prefix(node["name"]),
                source_schema=node["schema"],
                source_relation=node.get("alias") or node["name"],
                columns=cols,
                description=(node.get("description") or "").strip(),
            )
        )
    wrappers.sort(key=lambda w: w.view_name)
    return wrappers


# --- SQL emission ----------------------------------------------------------


def _quote_literal(s: str) -> str:
    """Postgres single-quoted string with embedded ' doubled."""
    return "'" + s.replace("'", "''") + "'"


def _wrap_for_sql_comment(s: str) -> str:
    """Single-line for SQL header comments; collapse newlines."""
    return s.replace("\n", " ").replace("\r", "").strip()


def render_sql(wrappers: list[WrapperView], removed_views: list[str]) -> str:
    """Build the migration SQL body. Deterministic; safe to diff."""
    out: list[str] = [
        "-- atlas-data/dbt/api_v1_generated.sql",
        "-- AUTO-GENERATED by atlas-data/dbt/scripts/generate_api_v1.py — do not hand-edit.",
        "-- Re-running ./regenerate-api-v1.sh after a dbt-model change is the source of truth.",
        "--",
        "-- Apply via ./apply-api-v1.sh AFTER `dbt run` — the wrappers reference",
        "-- marts.mart_* tables which only exist after dbt has built them.",
        "-- All statements are idempotent (CREATE OR REPLACE / IF NOT EXISTS / DROP IF EXISTS).",
        "--",
        "-- For design rationale see:",
        "--   website/docs/ai-developer/plans/active/PLAN-004-postgrest-api-v1-wrapper.md",
        "--",
        "-- ROLLBACK: undeploy + purge UIS first (./uis undeploy postgrest --app atlas",
        "-- + ./uis configure postgrest --app atlas --purge), then DROP SCHEMA api_v1 CASCADE.",
        "",
        "CREATE SCHEMA IF NOT EXISTS api_v1;",
        "",
    ]

    if removed_views:
        out.append("-- Views removed since the previous generation (PLAN-004 [Q17])")
        for v in removed_views:
            out.append(f"DROP VIEW IF EXISTS api_v1.{v} CASCADE;")
        out.append("")

    for w in wrappers:
        fq_source = f"{w.source_schema}.{w.source_relation}"
        out.append(f"-- {w.view_name}  ←  {fq_source}")
        out.append(
            f"CREATE OR REPLACE VIEW api_v1.{w.view_name} AS SELECT * FROM {fq_source};"
        )
        if w.description:
            out.append(
                f"COMMENT ON VIEW api_v1.{w.view_name} IS "
                f"{_quote_literal(w.description)};"
            )
        for c in w.columns:
            if c.description:
                out.append(
                    f"COMMENT ON COLUMN api_v1.{w.view_name}.{c.name} IS "
                    f"{_quote_literal(c.description)};"
                )
        out.append("")

    # 🔴 THIS GRANT IS SELECT-ONLY AND THE OpenAPI DOCUMENT WILL CONTRADICT IT.
    # DO NOT TRY TO FIX THAT HERE, AND ESPECIALLY NOT WITH openapi-mode.
    #
    # PostgREST advertises post/patch/delete on 15 of the 17 api_v1 relations.
    # Every one is refused by Postgres — 42501, probed live by ops-dev on
    # 2026-09-20 (urb-agents #1284). Nothing is exposed; the document is wrong.
    #
    # The dead ends, so nobody re-walks them (tor-agent, #1296):
    #
    #   openapi-mode = follow-privileges   Not configured ANYWHERE, so the
    #                                      upstream default applies and setting
    #                                      it explicitly is a no-op.
    #
    #                                      ⚠️ Provenance, because it was
    #                                      overstated once (#1303). MEASURED
    #                                      unset in four places: the pod spec
    #                                      env, the process at pid 1,
    #                                      pg_roles.rolconfig and
    #                                      pg_db_role_setting — PostgREST reads
    #                                      configuration from the database as
    #                                      well as the environment, and the
    #                                      first report checked only the
    #                                      environment. INFERRED, and still
    #                                      inferred: that unset means
    #                                      follow-privileges. No PostgREST
    #                                      endpoint reports the effective
    #                                      setting — the admin server exposes
    #                                      /live, /ready and /metrics, not
    #                                      /config — so nobody can close that
    #                                      last link from outside.
    #   openapi-mode = ignore-privileges   ⚠️ The only value that changes
    #                                      anything, and it advertises every
    #                                      method REGARDLESS of grants by
    #                                      design. It would make the defect
    #                                      permanent while looking like a fix.
    #   a stale privilege cache            Falsified. publish_api_v1 ends with
    #                                      NOTIFY pgrst, 'reload schema'; the
    #                                      10:07 run on 2026-09-20 provably
    #                                      reloaded (new comment text went live)
    #                                      and the method counts were unchanged.
    #   adding REVOKE statements here      Revoking what was never granted is a
    #                                      no-op on both the grant and the spec.
    #
    # ✅ It is structural: PostgREST v14.10 advertises writes for any
    # AUTO-UPDATABLE view, independently of who may write it. The only two
    # relations that do not advertise are kommune_ngo_summary and
    # kommune_ngo_totals — the only two that GROUP BY. Same structural line that
    # decides whether count=estimated is accurate.
    #
    # 🔵 So documentation is the layer, permanently, not as a stopgap. I called
    # it "the wrong layer, pending a platform fix"; there is no platform fix
    # short of an upstream PostgREST change. An external consumer had already
    # encoded the advertisement as a structural fact — it derived
    # table-versus-view from the write verbs and mislabelled 15 relations since
    # its first commit — which is why this is worth a comment and not a shrug.
    #
    # Guarded grants. UIS's ./uis configure postgrest creates atlas_web_anon
    # (per their INVESTIGATE-postgrest.md) but isn't yet implemented. The DO
    # block lets this migration apply both before and after UIS runs configure
    # — see PLAN-004 [Q11/Q12](ii).
    #
    # ⚠️ DO NOT delete these as "duplicating what ./uis configure already does".
    # They look redundant and are not.
    #
    # `ALTER DEFAULT PRIVILEGES` applies only to objects created by the role that
    # SET it. UIS's configure runs as `postgres`, so its default ACL reads
    # `atlas_web_anon=r/postgres` and covers objects postgres creates. The api_v1
    # views are created by the `atlas` role, by this SQL — so the platform's
    # default privileges do not reach them.
    #
    # This block is therefore the thing that keeps the public API working across a
    # refresh: every `dbt run` drops the api_v1 views via CASCADE, the api_v1 asset
    # re-creates them as `atlas`, and it is the ALTER DEFAULT PRIVILEGES below —
    # owned by `atlas` — that makes the new views readable by the anon role.
    # Remove it and the API goes dark after the next transform, silently, with the
    # views present and empty of permission rather than of rows.
    #
    # Verified locally 2026-08-25: a view created as `atlas` in api_v1 is readable
    # by atlas_web_anon, and pg_default_acl shows `atlas ... {atlas_web_anon=r/atlas}`
    # — set by this block, not by the platform.
    out.extend(
        [
            "-- Grant SELECT to the per-app anon role if it exists (created by UIS's",
            "-- ./uis configure postgrest --app atlas). Guarded so this migration",
            "-- applies cleanly against environments where UIS hasn't run configure yet.",
            "DO $$ BEGIN",
            "  IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'atlas_web_anon') THEN",
            "    GRANT USAGE ON SCHEMA api_v1 TO atlas_web_anon;",
            "    GRANT SELECT ON ALL TABLES IN SCHEMA api_v1 TO atlas_web_anon;",
            "    ALTER DEFAULT PRIVILEGES IN SCHEMA api_v1",
            "      GRANT SELECT ON TABLES TO atlas_web_anon;",
            "  END IF;",
            "END $$;",
            "",
            "-- Tell PostgREST to reload its schema cache so newly-added or removed",
            "-- views surface immediately. No-op if no PostgREST is listening.",
            "NOTIFY pgrst, 'reload schema';",
            "",
        ]
    )
    return "\n".join(out)


def render_state(wrappers: list[WrapperView]) -> str:
    """The state file: just the list of view names, sorted, JSON-formatted."""
    payload = {
        "format_version": 1,
        "views": sorted(w.view_name for w in wrappers),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


# --- CLI -------------------------------------------------------------------


def _read_state(path: Path) -> list[str]:
    if not path.exists():
        return []
    data = json.loads(path.read_text())
    return list(data.get("views", []))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--manifest", required=True, type=Path, help="Path to target/manifest.json")
    p.add_argument(
        "--models-dir-prefix",
        default="models/marts/api/",
        help='Filter manifest models by original_file_path prefix (default "models/marts/api/")',
    )
    p.add_argument(
        "--state",
        required=True,
        type=Path,
        help="Path to api_v1_state.json (read previous, write new)",
    )
    p.add_argument("--out", required=True, type=Path, help="Output SQL migration path")
    args = p.parse_args()

    manifest = json.loads(args.manifest.read_text())
    wrappers = extract_wrappers(manifest, args.models_dir_prefix)

    prev_views = set(_read_state(args.state))
    current_views = {w.view_name for w in wrappers}
    removed = sorted(prev_views - current_views)

    sql = render_sql(wrappers, removed)
    state = render_state(wrappers)

    args.out.write_text(sql)
    args.state.write_text(state)
    print(
        f"wrote {args.out} ({len(wrappers)} wrappers, "
        f"{len(removed)} removed) and {args.state}"
    )


if __name__ == "__main__":
    main()
