#!/usr/bin/env bash
# Regenerate docs/stack/erd.md from current dbt artifacts.
#
# dbterd writes raw Mermaid `erDiagram` syntax with no fence. GitHub needs
# a ```mermaid``` block to render it, so this wrapper:
#   1. Refreshes the dbt manifest+catalog (dbt docs generate).
#   2. Runs dbterd with the project's .dbterd.yml settings.
#   3. Prepends a "do not edit" header + wraps the body in a mermaid fence.
#
# Run from atlas-data-repo/dbt/. See README.md for context.

set -euo pipefail

cd "$(dirname "$0")"

ERD_PATH="../../docs/stack/erd.md"

uv run --env-file ../ingest/.env dbt docs generate >/dev/null
uv run dbterd run

TMP="$(mktemp)"
{
  echo "<!--"
  echo "  Generated by dbterd from atlas-data-repo/dbt/ artifacts."
  echo "  DO NOT EDIT BY HAND. Regenerate via atlas-data-repo/dbt/regenerate-erd.sh"
  echo "  Last regenerated: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "-->"
  echo
  echo "# Atlas marts ERD"
  echo
  echo "Entity-relationship view of the \`marts.*\` schema. Edges are derived"
  echo "from \`relationships:\` data tests in the per-model \`schema.yml\` files."
  echo "See [naming-conventions.md](naming-conventions.md) for the canonical"
  echo "vocabulary and [the dbt README](../../atlas-data-repo/dbt/README.md)"
  echo "for how to regenerate this file."
  echo
  echo '```mermaid'
  cat "$ERD_PATH"
  echo '```'
} > "$TMP"

mv "$TMP" "$ERD_PATH"
echo "Wrote $ERD_PATH"
