/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent alle tjenester */
        get: operations["listTjenester"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enheter": {
        parameters: {
            query?: {
                /** @description Antall ønskede treff i response. Default verdi er 20. Max dypde (page*size) er 10 000. */
                size?: number;
                /** @description Hvilken side som ønskes av resultatsettet. Default verdi er 0. Max dypde (page*size) er 10 000 */
                page?: number;
                /** @description Filtrer på navn. Sammensatt søk på likhet. Resultat sorteres pr default etter score */
                navn?: string;
                /** @description Sorter resultatsett på feltnavn. Merk at navn må sorteres på navn.norwegian */
                sort?: string;
                /** @description Filtrer på organisasjonsformkode. Kommaseparert liste. */
                organisasjonsform?: string;
                /** @description Filtrer på næringskode. Valgfritt nivå. Kommaseparert liste. */
                naeringskode?: string;
                /** @description Filtrer på kommunenummer 4 siffer. */
                kommunenummer?: string;
                /** @description Organisasjonsnummeret til overordnet enhet */
                overordnetEnhet?: string;
                /** @description Filtrer på fra registreringsdato i Enhetsregisteret. */
                fraRegistreringsdatoEnhetsregisteret?: string;
                /** @description Filtrer på til registreringsdato i Enhetsregisteret. */
                tilRegistreringsdatoEnhetsregisteret?: string;
                /** @description Filtrer på om enheten er registrert i Merverdiregisteret */
                registrertIMvaregisteret?: boolean;
                /** @description Filtrer på om enheten er registrert konkurs */
                konkurs?: boolean;
                /** @description Filtrer på fra antall ansatte */
                fraAntallAnsatte?: number;
                /** @description Filtrer på til antall ansatte */
                tilAntallAnsatte?: number;
                /** @description Organisasjonsnummeret til enhetene.  Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
                /** @description Hvorvidt enheten er registrert i Foretaksregisteret */
                registrertIForetaksregisteret?: boolean;
                /** @description Hvorvidt enheten er registrert i Stiftelsesregisteret */
                registrertIStiftelsesregisteret?: boolean;
                /** @description Hvorvidt enheten er registrert i Frivillighetsregisteret */
                registrertIFrivillighetsregisteret?: boolean;
                /** @description Frivillig registrert i Merverdiavgiftsregisteret. Kommaseparert liste med beskrivelser. */
                frivilligRegistrertIMvaregisteret?: string;
                /** @description Hvorvidt enheten er registrert som underTvangsavvikling eller tvangsopplosning */
                underTvangsavviklingEllerTvangsopplosning?: boolean;
                /** @description Hvorvidt enheten er registrert som underAvvikling */
                underAvvikling?: boolean;
                /** @description Tidligste stiftelsesdato for enheten */
                fraStiftelsesdato?: string;
                /** @description Seneste stiftelsesdato hos enheten */
                tilStiftelsesdato?: string;
                /** @description Enhetens hjemmeside */
                hjemmeside?: string;
                /** @description Enhetens institusjonelle sektorkode. Kommaseparert liste med sektorkoder på 4 siffer. */
                institusjonellSektorkode?: string;
                /** @description Kommunenummer til enhetens postadresse. Kommaseparert liste med kommunenummer på 4 siffer. */
                "postadresse.kommunenummer"?: string;
                /** @description Postnummeret til enhetens postadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "postadresse.postnummer"?: string;
                /** @description Poststedet til enhetens postadresse. Fritekst. */
                "postadresse.poststed"?: string;
                /** @description Landkode til enhetens postadresse. Kommaseparert liste med landkoder. */
                "postadresse.landkode"?: string;
                /** @description Adresse til enhetens postadresse. Kommaseparert liste med adresser. */
                "postadresse.adresse"?: string;
                /** @description Postnummer til enhetens forretningsadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "forretningsadresse.postnummer"?: string;
                /** @description Poststedet til enhetens forretningsadresse. Fritekst. */
                "forretningsadresse.poststed"?: string;
                /** @description Landkode til enhetens forretningsadresse. Kommaseparert liste med landkoder. */
                "forretningsadresse.landkode"?: string;
                /** @description Adresse til enhetens forretningsadresse. Kommaseparert liste med adresser. */
                "forretningsadresse.adresse"?: string;
                /** @description Årstall for siste innsendte årsregnskap for enheten. Kommaseparert liste med årstall på 4 siffer */
                sisteInnsendteAarsregnskap?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent alle enheter */
        get: operations["listEnheter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enheter/{organisasjonsnummer}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organisasjonsnummeret til enheten - 9 siffer */
                organisasjonsnummer: string;
            };
            cookie?: never;
        };
        /** @description Hent detaljer om enhet */
        get: operations["hentEnhet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/underenheter": {
        parameters: {
            query?: {
                /** @description Filtrer på navn. Sammensatt søk på likhet. Resultat sorteres pr default etter score */
                navn?: string;
                /** @description Organisasjonsnummeret til underenhetene.  Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
                /** @description Organisasjonsnummeret til overordnet enhet */
                overordnetEnhet?: string;
                /** @description Filtrer på fra antall ansatte */
                fraAntallAnsatte?: number;
                /** @description Filtrer på til antall ansatte */
                tilAntallAnsatte?: number;
                /** @description Filtrer på om enheten er registrert i Merverdiregisteret */
                registrertIMvaregisteret?: boolean;
                /** @description Filtrer på fra registreringsdato i Enhetsregisteret. */
                fraRegistreringsdatoEnhetsregisteret?: string;
                /** @description Filtrer på til registreringsdato i Enhetsregisteret. */
                tilRegistreringsdatoEnhetsregisteret?: string;
                /** @description Tidligste oppstartsdato for enheten */
                fraOppstartsdato?: string;
                /** @description Seneste oppstartsdato for enheten */
                tilOppstartsdato?: string;
                /** @description Tidligste registreringsdato for eierskifte */
                fraDatoEierskifte?: string;
                /** @description Seneste registreringsdato for eierskifte */
                tilDatoEierskifte?: string;
                /** @description Tidligste nedleggelsesdato for enheten */
                fraNedleggelsesdato?: string;
                /** @description Seneste nedleggelsesdato for enheten */
                tilNedleggelsesdato?: string;
                /** @description Filtrer på organisasjonsformkode. Kommaseparert liste. */
                organisasjonsform?: string;
                /** @description Enhetens hjemmeside */
                hjemmeside?: string;
                /** @description Kommunenummer til enhetens postadresse. Kommaseparert liste med kommunenummer på 4 siffer. */
                "postadresse.kommunenummer"?: string;
                /** @description Postnummeret til enhetens postadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "postadresse.postnummer"?: string;
                /** @description Poststedet til enhetens postadresse. Fritekst. */
                "postadresse.poststed"?: string;
                /** @description Landkode til enhetens postadresse. Kommaseparert liste med landkoder. */
                "postadresse.landkode"?: string;
                /** @description Adresse til enhetens postadresse. Kommaseparert liste med adresser. */
                "postadresse.adresse"?: string;
                /** @description Filtrer på kommunenummer 4 siffer. */
                kommunenummer?: string;
                /** @description Postnummeret til enhetens beliggenhetsadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "beliggenhetsadresse.postnummer"?: string;
                /** @description Poststedet til enhetens beliggenhetsadresse. Fritekst. */
                "beliggenhetsadresse.poststed"?: string;
                /** @description Landkode til enhetens beliggenhetsadresse. Kommaseparert liste med landkoder. */
                "beliggenhetsadresse.landkode"?: string;
                /** @description Adresse til enhetens beliggenhetsadresse. Kommaseparert liste med adresser. */
                "beliggenhetsadresse.adresse"?: string;
                /** @description Filtrer på næringskode. Valgfritt nivå. Kommaseparert liste. */
                naeringskode?: string;
                /** @description Sorter resultatsett på feltnavn. Merk at navn må sorteres på navn.norwegian */
                sort?: string;
                /** @description Antall ønskede treff i response. Default verdi er 20. Max dypde (page*size) er 10 000. */
                size?: number;
                /** @description Hvilken side som ønskes av resultatsettet. Default verdi er 0. Max dypde (page*size) er 10 000 */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent alle underenheter */
        get: operations["listUnderenheter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/underenheter/{organisasjonsnummer}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organisasjonsnummeret til underenheten - 9 siffer */
                organisasjonsnummer: string;
            };
            cookie?: never;
        };
        /** @description Hent detaljer om underenhet */
        get: operations["hentUnderenhet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppdateringer/enheter": {
        parameters: {
            query?: {
                /** @description Tidligste tidsstempel for når enheten ble oppdatert. På format Datetime (ISO-8601): yyyy-MM-dd'T'HH:mm:ss.SSS'Z' */
                dato?: string;
                /** @description Minste oppdateringsid for enhet. Større eller lik 1. */
                oppdateringsid?: number;
                /** @description Organisasjonsnummeret til enheten. Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent oppdateringer på enheter */
        get: operations["listOppdateringerEnhet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppdateringer/underenheter": {
        parameters: {
            query?: {
                /** @description Tidligste tidsstempel for når enheten ble oppdatert. På format Datetime (ISO-8601): yyyy-MM-dd'T'HH:mm:ss.SSS'Z' */
                dato?: string;
                /** @description Minste oppdateringsid for enhet. Større eller lik 1. */
                oppdateringsid?: number;
                /** @description Organisasjonsnummeret til enheten. Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent oppdateringer på underenheter */
        get: operations["listOppdateringerUnderenhet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisasjonsformer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent alle organisasjonsformer */
        get: operations["listOrganisasjonsformer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisasjonsformer/{orgformKode}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kode for organisasjonsform */
                orgformKode: string;
            };
            cookie?: never;
        };
        /** @description Hent en enkelt organisasjonsform fra kode */
        get: operations["hentOrganisasjonsform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisasjonsformer/enheter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent organisasjonsformer for enheter */
        get: operations["listOrganisasjonsformerEnheter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisasjonsformer/underenheter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hent organisasjonsformer for underenheter */
        get: operations["listOrganisasjonsformerUnderenheter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Enhet: {
            organisasjonsnummer?: string;
            navn?: string;
            organisasjonsform?: components["schemas"]["Organisasjonsform"];
            registreringsdatoEnhetsregisteret?: string;
            registrertIMvaregisteret?: boolean;
            naeringskode1?: components["schemas"]["Naeringskode"];
            naeringskode2?: components["schemas"]["Naeringskode"];
            naeringskode3?: components["schemas"]["Naeringskode"];
            antallAnsatte?: number;
            stiftelsedato?: string;
            institusjonellSektorkode?: components["schemas"]["Sektorkode"];
            registrertIForetaksregisteret?: boolean;
            registrertIStiftelsesregisteret?: boolean;
            registrertIFrivillighetsregisteret?: boolean;
            sisteInnsendteAarsregnskap?: string;
            konkurs?: boolean;
            underAvvikling?: boolean;
            underTvangsavviklingEllerTvangsopplosning?: boolean;
            maalform?: string;
            _links?: components["schemas"]["Self"];
        };
        Naeringskode: {
            kode?: string;
            beskrivelse?: string;
        };
        Sektorkode: {
            kode?: string;
            beskrivelse?: string;
        };
        _Organisasjonsformer: {
            embedded?: components["schemas"]["Organisasjonsformer"];
        };
        Organisasjonsformer: {
            organisasjonsformer?: components["schemas"]["Organisasjonsform"][];
        };
        Organisasjonsform: {
            kode?: string;
            beskrivelse?: string;
            _links?: components["schemas"]["Self"];
        };
        Self: {
            self?: components["schemas"]["Href"];
        };
        Href: {
            href?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTjenester: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tjenester mot åpne data fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEnheter: {
        parameters: {
            query?: {
                /** @description Antall ønskede treff i response. Default verdi er 20. Max dypde (page*size) er 10 000. */
                size?: number;
                /** @description Hvilken side som ønskes av resultatsettet. Default verdi er 0. Max dypde (page*size) er 10 000 */
                page?: number;
                /** @description Filtrer på navn. Sammensatt søk på likhet. Resultat sorteres pr default etter score */
                navn?: string;
                /** @description Sorter resultatsett på feltnavn. Merk at navn må sorteres på navn.norwegian */
                sort?: string;
                /** @description Filtrer på organisasjonsformkode. Kommaseparert liste. */
                organisasjonsform?: string;
                /** @description Filtrer på næringskode. Valgfritt nivå. Kommaseparert liste. */
                naeringskode?: string;
                /** @description Filtrer på kommunenummer 4 siffer. */
                kommunenummer?: string;
                /** @description Organisasjonsnummeret til overordnet enhet */
                overordnetEnhet?: string;
                /** @description Filtrer på fra registreringsdato i Enhetsregisteret. */
                fraRegistreringsdatoEnhetsregisteret?: string;
                /** @description Filtrer på til registreringsdato i Enhetsregisteret. */
                tilRegistreringsdatoEnhetsregisteret?: string;
                /** @description Filtrer på om enheten er registrert i Merverdiregisteret */
                registrertIMvaregisteret?: boolean;
                /** @description Filtrer på om enheten er registrert konkurs */
                konkurs?: boolean;
                /** @description Filtrer på fra antall ansatte */
                fraAntallAnsatte?: number;
                /** @description Filtrer på til antall ansatte */
                tilAntallAnsatte?: number;
                /** @description Organisasjonsnummeret til enhetene.  Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
                /** @description Hvorvidt enheten er registrert i Foretaksregisteret */
                registrertIForetaksregisteret?: boolean;
                /** @description Hvorvidt enheten er registrert i Stiftelsesregisteret */
                registrertIStiftelsesregisteret?: boolean;
                /** @description Hvorvidt enheten er registrert i Frivillighetsregisteret */
                registrertIFrivillighetsregisteret?: boolean;
                /** @description Frivillig registrert i Merverdiavgiftsregisteret. Kommaseparert liste med beskrivelser. */
                frivilligRegistrertIMvaregisteret?: string;
                /** @description Hvorvidt enheten er registrert som underTvangsavvikling eller tvangsopplosning */
                underTvangsavviklingEllerTvangsopplosning?: boolean;
                /** @description Hvorvidt enheten er registrert som underAvvikling */
                underAvvikling?: boolean;
                /** @description Tidligste stiftelsesdato for enheten */
                fraStiftelsesdato?: string;
                /** @description Seneste stiftelsesdato hos enheten */
                tilStiftelsesdato?: string;
                /** @description Enhetens hjemmeside */
                hjemmeside?: string;
                /** @description Enhetens institusjonelle sektorkode. Kommaseparert liste med sektorkoder på 4 siffer. */
                institusjonellSektorkode?: string;
                /** @description Kommunenummer til enhetens postadresse. Kommaseparert liste med kommunenummer på 4 siffer. */
                "postadresse.kommunenummer"?: string;
                /** @description Postnummeret til enhetens postadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "postadresse.postnummer"?: string;
                /** @description Poststedet til enhetens postadresse. Fritekst. */
                "postadresse.poststed"?: string;
                /** @description Landkode til enhetens postadresse. Kommaseparert liste med landkoder. */
                "postadresse.landkode"?: string;
                /** @description Adresse til enhetens postadresse. Kommaseparert liste med adresser. */
                "postadresse.adresse"?: string;
                /** @description Postnummer til enhetens forretningsadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "forretningsadresse.postnummer"?: string;
                /** @description Poststedet til enhetens forretningsadresse. Fritekst. */
                "forretningsadresse.poststed"?: string;
                /** @description Landkode til enhetens forretningsadresse. Kommaseparert liste med landkoder. */
                "forretningsadresse.landkode"?: string;
                /** @description Adresse til enhetens forretningsadresse. Kommaseparert liste med adresser. */
                "forretningsadresse.adresse"?: string;
                /** @description Årstall for siste innsendte årsregnskap for enheten. Kommaseparert liste med årstall på 4 siffer */
                sisteInnsendteAarsregnskap?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enheter fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Ugyldig forespørsel */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hentEnhet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organisasjonsnummeret til enheten - 9 siffer */
                organisasjonsnummer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enhet fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enhet"];
                    "application/vnd.enhetsregisteret.enhet.v1+json": components["schemas"]["Enhet"];
                };
            };
            /** @description Enheten finnes ikke */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Enheten er fjernet */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUnderenheter: {
        parameters: {
            query?: {
                /** @description Filtrer på navn. Sammensatt søk på likhet. Resultat sorteres pr default etter score */
                navn?: string;
                /** @description Organisasjonsnummeret til underenhetene.  Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
                /** @description Organisasjonsnummeret til overordnet enhet */
                overordnetEnhet?: string;
                /** @description Filtrer på fra antall ansatte */
                fraAntallAnsatte?: number;
                /** @description Filtrer på til antall ansatte */
                tilAntallAnsatte?: number;
                /** @description Filtrer på om enheten er registrert i Merverdiregisteret */
                registrertIMvaregisteret?: boolean;
                /** @description Filtrer på fra registreringsdato i Enhetsregisteret. */
                fraRegistreringsdatoEnhetsregisteret?: string;
                /** @description Filtrer på til registreringsdato i Enhetsregisteret. */
                tilRegistreringsdatoEnhetsregisteret?: string;
                /** @description Tidligste oppstartsdato for enheten */
                fraOppstartsdato?: string;
                /** @description Seneste oppstartsdato for enheten */
                tilOppstartsdato?: string;
                /** @description Tidligste registreringsdato for eierskifte */
                fraDatoEierskifte?: string;
                /** @description Seneste registreringsdato for eierskifte */
                tilDatoEierskifte?: string;
                /** @description Tidligste nedleggelsesdato for enheten */
                fraNedleggelsesdato?: string;
                /** @description Seneste nedleggelsesdato for enheten */
                tilNedleggelsesdato?: string;
                /** @description Filtrer på organisasjonsformkode. Kommaseparert liste. */
                organisasjonsform?: string;
                /** @description Enhetens hjemmeside */
                hjemmeside?: string;
                /** @description Kommunenummer til enhetens postadresse. Kommaseparert liste med kommunenummer på 4 siffer. */
                "postadresse.kommunenummer"?: string;
                /** @description Postnummeret til enhetens postadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "postadresse.postnummer"?: string;
                /** @description Poststedet til enhetens postadresse. Fritekst. */
                "postadresse.poststed"?: string;
                /** @description Landkode til enhetens postadresse. Kommaseparert liste med landkoder. */
                "postadresse.landkode"?: string;
                /** @description Adresse til enhetens postadresse. Kommaseparert liste med adresser. */
                "postadresse.adresse"?: string;
                /** @description Filtrer på kommunenummer 4 siffer. */
                kommunenummer?: string;
                /** @description Postnummeret til enhetens beliggenhetsadresse. Kommaseparert liste med postnummer på 4 siffer. */
                "beliggenhetsadresse.postnummer"?: string;
                /** @description Poststedet til enhetens beliggenhetsadresse. Fritekst. */
                "beliggenhetsadresse.poststed"?: string;
                /** @description Landkode til enhetens beliggenhetsadresse. Kommaseparert liste med landkoder. */
                "beliggenhetsadresse.landkode"?: string;
                /** @description Adresse til enhetens beliggenhetsadresse. Kommaseparert liste med adresser. */
                "beliggenhetsadresse.adresse"?: string;
                /** @description Filtrer på næringskode. Valgfritt nivå. Kommaseparert liste. */
                naeringskode?: string;
                /** @description Sorter resultatsett på feltnavn. Merk at navn må sorteres på navn.norwegian */
                sort?: string;
                /** @description Antall ønskede treff i response. Default verdi er 20. Max dypde (page*size) er 10 000. */
                size?: number;
                /** @description Hvilken side som ønskes av resultatsettet. Default verdi er 0. Max dypde (page*size) er 10 000 */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Underenheter fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hentUnderenhet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organisasjonsnummeret til underenheten - 9 siffer */
                organisasjonsnummer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Underenhet fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Underenhet finnes ikke */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Underenhet er fjernet */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOppdateringerEnhet: {
        parameters: {
            query?: {
                /** @description Tidligste tidsstempel for når enheten ble oppdatert. På format Datetime (ISO-8601): yyyy-MM-dd'T'HH:mm:ss.SSS'Z' */
                dato?: string;
                /** @description Minste oppdateringsid for enhet. Større eller lik 1. */
                oppdateringsid?: number;
                /** @description Organisasjonsnummeret til enheten. Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oppdateringer på enheter fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOppdateringerUnderenhet: {
        parameters: {
            query?: {
                /** @description Tidligste tidsstempel for når enheten ble oppdatert. På format Datetime (ISO-8601): yyyy-MM-dd'T'HH:mm:ss.SSS'Z' */
                dato?: string;
                /** @description Minste oppdateringsid for enhet. Større eller lik 1. */
                oppdateringsid?: number;
                /** @description Organisasjonsnummeret til enheten. Kommaseparert liste med organisasjonsnummer. */
                organisasjonsnummer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oppdateringer på underenheter fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOrganisasjonsformer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organisasjonsformer fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_Organisasjonsformer"];
                    "application/vnd.enhetsregisteret.organisasjonsform.v1+json": components["schemas"]["_Organisasjonsformer"];
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hentOrganisasjonsform: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kode for organisasjonsform */
                orgformKode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organisasjonsform fra Enhetsregisteret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisasjonsform"];
                    "application/vnd.enhetsregisteret.organisasjonsform.v1+json": components["schemas"]["Organisasjonsform"];
                };
            };
            /** @description Organisasjonsformen eksisterer ikke */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOrganisasjonsformerEnheter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste over mulige organisasjonsformer for enheter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOrganisasjonsformerUnderenheter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste over mulige organisasjonsformer for underenheter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Udefinert feil */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
