/**
 * /data/sources — sources index page (PLAN-007 phase 4 scaffold).
 *
 * Lists every ingest source Atlas knows about by reading `api_v1.meta_sources`
 * at runtime. The endpoint is generated by `mart_meta_sources` (PLAN-007
 * phase 3) and carries per-source manifest metadata + freshness signals from
 * `raw.ingest_runs` aggregates.
 *
 * Same introspection-driven pattern as the existing /data catalog: no
 * hardcoded source list, no copy of `_sources_manifest`. Adding a new
 * source via the cloud-agent pipeline + dbt seed makes it appear here on
 * next page load.
 *
 * This is a Phase 4 *scaffold* — minimal viable shape. Open follow-ups for
 * later iterations: tag-filter sidebar (PLAN-007 phase 4 task 4.1 with
 * URL-driven filter state), per-source detail page at
 * `/data/sources/[source_id]/page.tsx` showing downstream models +
 * dimensions, free-text search.
 */

import Link from "next/link";

export const revalidate = 60;

const API_URL =
  process.env.NEXT_PUBLIC_API_URL ?? "http://api-atlas.localhost";

type MetaSource = {
  source_id: string;
  upstream_url: string;
  upstream_landing_page: string | null;
  upstream_title: string;
  description: string;
  publisher: string;
  license: string;
  periodicity: string;
  eu_theme: string;
  tags: string[];
  last_ingested_at: string | null;
  last_upstream_update_at: string | null;
  latest_row_count: number | null;
  total_runs: number;
  downstream_model_count: number;
};

async function fetchSources(): Promise<MetaSource[]> {
  const res = await fetch(`${API_URL}/meta_sources?order=source_id`, {
    next: { revalidate: 60 },
  });
  if (!res.ok) {
    throw new Error(
      `meta_sources fetch failed: HTTP ${res.status} ${res.statusText}`,
    );
  }
  return (await res.json()) as MetaSource[];
}

/** Group an array of sources by a tag namespace (e.g. "provider", "topic"). */
function groupByNamespace(
  sources: MetaSource[],
  namespace: string,
): Map<string, MetaSource[]> {
  const groups = new Map<string, MetaSource[]>();
  const prefix = `${namespace}:`;
  for (const src of sources) {
    const tag = src.tags.find((t) => t.startsWith(prefix));
    const key = tag ? tag.slice(prefix.length) : "(unknown)";
    const list = groups.get(key) ?? [];
    list.push(src);
    groups.set(key, list);
  }
  return new Map([...groups.entries()].sort((a, b) => a[0].localeCompare(b[0])));
}

function relativeTime(iso: string | null): string {
  if (!iso) return "never";
  const then = new Date(iso).getTime();
  if (!Number.isFinite(then)) return iso;
  const days = Math.floor((Date.now() - then) / (1000 * 60 * 60 * 24));
  if (days < 1) return "today";
  if (days === 1) return "yesterday";
  if (days < 30) return `${days} days ago`;
  if (days < 365) return `${Math.floor(days / 30)} months ago`;
  return `${Math.floor(days / 365)} years ago`;
}

export default async function SourcesPage() {
  const sources = await fetchSources();
  const byProvider = groupByNamespace(sources, "provider");

  const totalRows = sources.reduce(
    (sum, s) => sum + (s.latest_row_count ?? 0),
    0,
  );

  return (
    <div className="min-h-screen bg-zinc-50 font-sans dark:bg-black">
      <main className="mx-auto flex w-full max-w-5xl flex-col gap-10 px-6 py-16">
        <header className="flex flex-col gap-3">
          <span className="text-sm font-medium uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Sources
          </span>
          <h1 className="text-3xl font-semibold tracking-tight text-zinc-950 dark:text-zinc-50">
            Atlas data sources
          </h1>
          <p className="max-w-3xl text-base leading-7 text-zinc-600 dark:text-zinc-400">
            Every upstream Atlas ingests. Currently {sources.length} sources
            across {byProvider.size} providers, {totalRows.toLocaleString()}{" "}
            total rows in the latest snapshot. Sourced live from{" "}
            <code className="rounded bg-zinc-200 px-1 text-xs dark:bg-zinc-800">
              api_v1.meta_sources
            </code>
            {" "}— see{" "}
            <Link href="/data" className="underline">
              /data
            </Link>
            {" "}for the full endpoint catalog.
          </p>
        </header>

        {[...byProvider.entries()].map(([provider, providerSources]) => (
          <section key={provider} className="flex flex-col gap-3">
            <h2 className="text-xl font-semibold tracking-tight text-zinc-950 dark:text-zinc-50">
              {provider}{" "}
              <span className="text-sm font-normal text-zinc-500 dark:text-zinc-400">
                ({providerSources.length})
              </span>
            </h2>
            <div className="flex flex-col gap-3">
              {providerSources.map((src) => (
                <article
                  key={src.source_id}
                  className="rounded-lg border border-zinc-200 bg-white p-4 transition-colors hover:border-zinc-300 dark:border-zinc-800 dark:bg-zinc-950 dark:hover:border-zinc-700"
                >
                  <div className="flex flex-wrap items-baseline justify-between gap-3">
                    <code className="font-mono text-sm font-medium text-zinc-950 dark:text-zinc-50">
                      {src.source_id}
                    </code>
                    <span className="text-xs text-zinc-500 dark:text-zinc-400">
                      ingested {relativeTime(src.last_ingested_at)} ·{" "}
                      {src.latest_row_count !== null
                        ? `${src.latest_row_count.toLocaleString()} rows`
                        : "no rows yet"}{" "}
                      · {src.downstream_model_count} downstream models
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-6 text-zinc-700 dark:text-zinc-300">
                    {src.description}
                  </p>
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {src.tags.map((tag) => (
                      <span
                        key={tag}
                        className="rounded-full bg-zinc-100 px-2 py-0.5 text-xs font-medium text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                  <div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-zinc-500 dark:text-zinc-400">
                    <a
                      href={src.upstream_landing_page ?? src.upstream_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-medium text-zinc-700 underline-offset-2 hover:underline dark:text-zinc-300"
                    >
                      Upstream ({src.publisher}) →
                    </a>
                    <span>License: {src.license}</span>
                    <span>Periodicity: {src.periodicity}</span>
                  </div>
                </article>
              ))}
            </div>
          </section>
        ))}

        <footer className="border-t border-zinc-200 pt-6 text-sm text-zinc-600 dark:border-zinc-800 dark:text-zinc-400">
          <p>
            Live from{" "}
            <code className="rounded bg-zinc-200 px-1.5 py-0.5 text-xs dark:bg-zinc-800">
              {API_URL}/meta_sources
            </code>
            . Tag-filter sidebar + per-source detail pages are{" "}
            <Link
              href="/data"
              className="font-medium text-zinc-700 underline-offset-2 hover:underline dark:text-zinc-300"
            >
              under construction
            </Link>{" "}
            as PLAN-007 phase 4 lands.
          </p>
        </footer>
      </main>
    </div>
  );
}
