/**
 * Types for sources-registry.json. Generated by website/scripts/
 * generate-sources-registry.mjs from per-source manifests. Keep this in
 * sync with the generator's output shape.
 */

export interface Dimension {
  code: string;
  meaning: string;
  value_format: string;
  notes: string;
}

export interface TimeCoverage {
  start: number | null;
  end: number | null;
}

export interface ManifestTags {
  provider: string;
  topic: string;
  geo: string;
  cadence: string;
}

export type Lifecycle = 'stable' | 'beta' | 'deprecated' | 'broken';

export interface ResolvedPublisher {
  id: string;
  display_name: string;
  homepage: string;
  logo: string;
}

export interface ResolvedCategory {
  id: string;
  name: string;
  emoji: string;
}

export interface Citation {
  text: string;
  bibtex: string;
}

export interface Source {
  source_id: string;
  upstream_id: string;
  upstream_url: string;
  upstream_landing_page: string | null;
  upstream_title: string;
  description: string;
  atlas_summary: string | null;
  publisher: ResolvedPublisher;
  category: ResolvedCategory;
  license: string;
  license_url: string;
  periodicity: string;
  eu_theme: string;
  attribution: string;
  tags: ManifestTags;
  keywords: string[];
  lifecycle: Lifecycle;
  time_coverage: TimeCoverage;
  methodology_notes: string | null;
  suggested_joins: string[];
  related_by_topic: string[];
  dimensions: Dimension[];
  raw_tables: string[] | null;
  sample_query: string;
  citation: Citation;
  feedback_url: string;
}

export interface Publisher {
  id: string;
  display_name: string;
  homepage: string;
  logo: string;
  feedback_url: string;
  notes: string;
  source_count: number;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  emoji: string;
  order: number;
  source_count: number;
}

export interface Registry {
  generated_at: string;
  manifest_schema_id: string | null;
  atlas_base_url: string;
  postgrest_base_url: string;
  categories: Category[];
  publishers: Publisher[];
  sources: Source[];
}
