/**
 * Types for sources-registry.json. Generated by website/scripts/
 * generate-sources-registry.mjs from per-source manifests. Keep this in
 * sync with the generator's output shape.
 */

export interface Dimension {
  code: string;
  meaning: string;
  value_format: string;
  notes: string;
}

export interface TimeCoverage {
  start: number | null;
  end: number | null;
}

export interface ManifestTags {
  provider: string;
  topic: string;
  geo: string;
  cadence: string;
}

export type Lifecycle = 'stable' | 'beta' | 'deprecated' | 'broken';

export interface ResolvedPublisher {
  id: string;
  display_name: string;
  homepage: string;
  logo: string;
}

export interface ResolvedCategory {
  id: string;
  name: string;
  emoji: string;
}

export interface Citation {
  text: string;
  bibtex: string;
}

export interface ConsumingMart {
  mart_name: string;
  api_v1_name: string;
  description_short: string | null;
  description_full: string | null;
  sample_query: string;
}

export type ConsumingModelKind =
  | 'mart' | 'indicators' | 'dim' | 'fact' | 'ref' | 'crosswalk' | 'other';

export interface ConsumingModel {
  name: string;
  kind: ConsumingModelKind;
}

export interface JoinedWith {
  source_id: string;
  shared_models: string[];
}

export interface ViewColumn {
  name: string;
  description: string;
}

export interface ViewBuiltFromSourceParent {
  parent_kind: 'source';
  source_id: string;
  upstream_title: string;
  publisher: { id: string; display_name: string; logo: string };
  category: { id: string; name: string; emoji: string };
}

export interface ViewBuiltFromModelParent {
  parent_kind: 'model';
  model_name: string;
  title: string | null;
  description_short: string | null;
}

export type ViewBuiltFromEntry = ViewBuiltFromSourceParent | ViewBuiltFromModelParent;

/**
 * View dataset — an api_v1.* PostgREST endpoint built by dbt, exposed in
 * the catalog at /datasets/<view_id>. The Atlas-built sibling of an upstream
 * Source dataset; same URL namespace, different kind.
 */
export interface View {
  kind: 'view';
  view_id: string;            // = api_v1_name, used as URL slug
  mart_name: string;          // e.g. mart_coverage_gap_barnefattigdom
  api_v1_name: string;        // mart_ prefix stripped
  title: string;              // human title from meta.title
  description_short: string;
  description_full: string;
  columns: ViewColumn[];
  built_from: ViewBuiltFromEntry[];
  sample_query: string;
  lineage_url: string;
}

export interface Source {
  kind: 'source';
  source_id: string;
  upstream_id: string;
  upstream_url: string;
  upstream_landing_page: string | null;
  upstream_title: string;
  description: string;
  atlas_summary: string | null;
  publisher: ResolvedPublisher;
  category: ResolvedCategory;
  license: string;
  license_url: string;
  periodicity: string;
  eu_theme: string;
  attribution: string;
  tags: ManifestTags;
  keywords: string[];
  lifecycle: Lifecycle;
  time_coverage: TimeCoverage;
  methodology_notes: string | null;
  suggested_joins: string[];
  related_by_topic: string[];
  dimensions: Dimension[];
  raw_tables: string[] | null;
  sample_query: string;
  citation: Citation;
  feedback_url: string;
  consuming_marts: ConsumingMart[];
  consuming_models: ConsumingModel[];
  joined_with: JoinedWith[];
  // Live freshness, sourced from api_v1.meta_sources via the snapshot script.
  // Null when no snapshot is available (graceful fallback for fresh repos /
  // first builds before the snapshot is captured).
  last_ingested_at: string | null;
  latest_row_count: number | null;
  total_runs: number | null;
  downstream_model_count: number | null;
}

export interface Publisher {
  id: string;
  display_name: string;
  homepage: string;
  logo: string;
  feedback_url: string;
  notes: string;
  source_count: number;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  emoji: string;
  order: number;
  source_count: number;
}

export interface Registry {
  generated_at: string;
  manifest_schema_id: string | null;
  atlas_base_url: string;
  postgrest_base_url: string;
  meta_sources_snapshot_at: string | null;
  categories: Category[];
  publishers: Publisher[];
  sources: Source[];
  views: View[];
}
