-- atlas-data/dbt/api_v1_generated.sql
-- AUTO-GENERATED by atlas-data/dbt/scripts/generate_api_v1.py — do not hand-edit.
-- Re-running ./regenerate-api-v1.sh after a dbt-model change is the source of truth.
--
-- Apply via ./apply-api-v1.sh AFTER `dbt run` — the wrappers reference
-- marts.mart_* tables which only exist after dbt has built them.
-- All statements are idempotent (CREATE OR REPLACE / IF NOT EXISTS / DROP IF EXISTS).
--
-- For design rationale see:
--   website/docs/ai-developer/plans/active/PLAN-004-postgrest-api-v1-wrapper.md
--
-- ROLLBACK: undeploy + purge UIS first (./uis undeploy postgrest --app atlas
-- + ./uis configure postgrest --app atlas --purge), then DROP SCHEMA api_v1 CASCADE.

CREATE SCHEMA IF NOT EXISTS api_v1;

-- activity_catalog  ←  marts.mart_activity_catalog
CREATE OR REPLACE VIEW api_v1.activity_catalog AS SELECT * FROM marts.mart_activity_catalog;
COMMENT ON VIEW api_v1.activity_catalog IS 'One row per (NGO, activity) joining dim_activity to the
service-category seed for the human-readable label, plus a count
of active chapters offering each activity. Backs the per-NGO
activity catalogue page (atlas-frontend
/ngo/[slug]/aktiviteter); equivalent to listActivities().

The full table is small (~35 rows for Red Cross alone in v1) and
grows as new NGOs land. PostgREST consumers filter via
?ngo_orgnr=eq.X.';
COMMENT ON COLUMN api_v1.activity_catalog.activity_id IS 'Composite slug (e.g. ''redcross-besokstjeneste''). Stable across
refreshes. Unique within this view.';
COMMENT ON COLUMN api_v1.activity_catalog.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO offering the activity.';
COMMENT ON COLUMN api_v1.activity_catalog.canonical_name IS 'Atlas''s canonical Norwegian name for the activity.';
COMMENT ON COLUMN api_v1.activity_catalog.service_category_code IS 'ICNPO-derived service category code (e.g. ''health'',
''social-services''). FK to ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.activity_catalog.service_category_label_no IS 'Human-readable Norwegian label for service_category_code,
joined from ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.activity_catalog.is_active IS 'Whether this activity is still offered by the NGO. Inactive
activities are kept so historical analysis can still resolve
activity_id values.';
COMMENT ON COLUMN api_v1.activity_catalog.chapter_count IS 'Count of distinct active chapters offering this activity. Zero
when the activity exists in dim_activity but no active chapter
provides it (rare but possible during transitions).';

-- brreg_enhet  ←  marts.mart_brreg_enhet
CREATE OR REPLACE VIEW api_v1.brreg_enhet AS SELECT * FROM marts.mart_brreg_enhet;
COMMENT ON VIEW api_v1.brreg_enhet IS 'Every organisation registered in Norway — the whole of Brønnøysundregistrene''s
Enhetsregisteret, around 1.17 million rows, current as of the last change-feed run.
Companies, foundations, associations, public bodies and sole proprietorships.

Kilde: Brønnøysundregistrene. Inneholder data under norsk lisens for offentlige data
(NLOD) tilgjengeliggjort av Brønnøysundregistrene — https://data.norge.no/nlod/no/2.0.
Re-users must carry this attribution onward; it is a condition of the licence, not a
courtesy.

Deleted organisations are excluded. Brreg reports deletions through its change feed and
Atlas applies them, so an organisation removed upstream disappears from here — but the
version history is kept, so what it looked like before removal remains answerable.

Completeness caveat: this reflects deletions Brreg REPORTS. A row Atlas holds that Brreg
never had would not be removed by any automatic path, because no change event would ever
mention it.';
COMMENT ON COLUMN api_v1.brreg_enhet.organisasjonsnummer IS 'Nine-digit Norwegian organisation number. Text, never a number — leading zeros are significant. Stable for the life of the organisation, and the join key for organisational data from any Norwegian source.';
COMMENT ON COLUMN api_v1.brreg_enhet.navn IS 'Registered name, verbatim from Brreg. For an enkeltpersonforetak (organisasjonsform ENK) this is very often the proprietor''s own personal name, because that is how the register records them.';
COMMENT ON COLUMN api_v1.brreg_enhet.organisasjonsform_kode IS 'Legal form code — AS (aksjeselskap), ENK (enkeltpersonforetak), FLI (forening/lag/innretning), STI (stiftelse) and others. The usual filter for separating companies from associations, or for excluding sole proprietorships.';
COMMENT ON COLUMN api_v1.brreg_enhet.organisasjonsform_beskrivelse IS 'Human-readable Norwegian label for organisasjonsform_kode, as Brreg publishes it.';
COMMENT ON COLUMN api_v1.brreg_enhet.naeringskode1_kode IS 'Primary NACE industry code (SN2007), e.g. 94.992. Null for roughly 2% of the register.';
COMMENT ON COLUMN api_v1.brreg_enhet.kommune_nr IS 'Kommune code of the registered business address. For an enkeltpersonforetak the registered business address is commonly the proprietor''s home address. Null where no business address is registered (~6%). Some codes are historical or pseudo-regions and will not resolve against a current kommune list.';
COMMENT ON COLUMN api_v1.brreg_enhet.antall_ansatte IS 'Registered employee count. NULL MEANS "NOT REPORTED", NOT ZERO — the field is present on only ~4% of records. Use har_registrert_antall_ansatte to distinguish the two; reading NULL as 0 understates staffed organisations badly.';
COMMENT ON COLUMN api_v1.brreg_enhet.har_registrert_antall_ansatte IS 'Whether Brreg holds a registered employee count at all. Present on 100% of records, and the only way to tell "zero employees" from "no figure reported".';
COMMENT ON COLUMN api_v1.brreg_enhet.konkurs IS 'Whether the organisation is in bankruptcy proceedings. Straight from Brreg.';
COMMENT ON COLUMN api_v1.brreg_enhet.under_avvikling IS 'Whether the organisation is being wound up voluntarily. Straight from Brreg.';
COMMENT ON COLUMN api_v1.brreg_enhet.under_tvangsavvikling IS 'Whether the organisation is under compulsory winding-up or dissolution.';
COMMENT ON COLUMN api_v1.brreg_enhet.is_active IS 'Convenience boolean — true when none of konkurs, under_avvikling or under_tvangsavvikling is set. Means "trading", not "exists": all three states are still registered organisations. Ignore this column if you want everything registered.';
COMMENT ON COLUMN api_v1.brreg_enhet.registrert_i_frivillighetsregisteret IS 'Whether the organisation is in Frivillighetsregisteret, the voluntary-organisation register — true for roughly 72,800 records. This is what makes the Norwegian voluntary sector discoverable as a population rather than a curated list.';
COMMENT ON COLUMN api_v1.brreg_enhet.registrert_dato IS 'Date the organisation was entered in Enhetsregisteret.';
COMMENT ON COLUMN api_v1.brreg_enhet.icnpo_nummer IS 'Primary ICNPO code as the organisation classified itself in Frivillighetsregisteret, e.g. "9100". Null for organisations not in that register, and for members declaring none. Null does not mean "not voluntary" — use registrert_i_frivillighetsregisteret for that.';
COMMENT ON COLUMN api_v1.brreg_enhet.icnpo_kategori IS 'Primary ICNPO category label paired with icnpo_nummer.';
COMMENT ON COLUMN api_v1.brreg_enhet.grasrotandel_deltar_i IS 'Whether the organisation participates in Grasrotandelen, Norsk Tipping''s grassroots funding scheme. Null for organisations not in Frivillighetsregisteret.';
COMMENT ON COLUMN api_v1.brreg_enhet.frivillig_innfoert_dato IS 'Date of entry in Frivillighetsregisteret — distinct from registrert_dato, which is the Enhetsregisteret entry. Organisations often exist for years before registering as voluntary.';
COMMENT ON COLUMN api_v1.brreg_enhet.last_seen_at IS 'When Atlas last wrote this row, from either the bulk snapshot or a change-feed run. Tracks Atlas''s load, not an upstream event.';
COMMENT ON COLUMN api_v1.brreg_enhet.doc IS 'The complete upstream record as Brreg published it, with nothing dropped or renamed — including postal and business addresses, telephone, mobile, email, website, capital, institutional sector code, articles of association and historical names. Responses are large: a document averages ~1.7 kB, so select the typed columns instead unless you need a field this view does not surface.';

-- bufdir_indicator_alias  ←  marts.mart_bufdir_indicator_alias
CREATE OR REPLACE VIEW api_v1.bufdir_indicator_alias AS SELECT * FROM marts.mart_bufdir_indicator_alias;
COMMENT ON VIEW api_v1.bufdir_indicator_alias IS 'Cross-release alias table for `bufdir-barnefattigdom`
`indicator_api_id` renumbers. One row per (historical_id,
canonical_id) mapping consumers join on for cross-time-series
continuity when Bufdir splits, retires, or renumbers a workbook
upstream — e.g. the observed `Indikator 9` → `9a` / `9b` split,
and `Indikator 10` retired without successor.

Thin republish of the editorial seed `bufdir_indicator_alias` so
the PLAN-004 generator auto-emits `api_v1.bufdir_indicator_alias`
(the leading `mart_` is stripped per `models/marts/api/README.md`
§ Naming).

See `website/docs/ai-developer/plans/active/PLAN-bufdir-surrogate-id-migration.md`
for design rationale + the maintenance ritual that appends rows
when a new Bufdir bundle release surfaces additional renumbering.';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.source_id IS 'Source the alias applies to. Always `bufdir-barnefattigdom`
today; forward-looking column kept so other ZIP sources can
adopt the same convention without a schema migration.';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.historical_id IS 'Previous `indicator_api_id` from an earlier bufdir release —
the id consumers may have cached and now need to bridge to
the current canonical id. Same shape as
`indicators__bufdir_barnefattigdom.indicator_api_id`
(`bf_zip_ind_<N>`).';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.canonical_id IS 'Current `indicator_api_id`, or NULL when the historical
indicator was retired without a successor. NULL is meaningful:
consumers treat such rows as terminating series rather than
orphans.';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.note IS 'Editorial explanation of the renumbering event — why the
historical id maps to this canonical id, or why no successor
exists. One sentence; read by humans, not parsers.';

-- coverage_gap_barnefattigdom  ←  marts.mart_coverage_gap_barnefattigdom
CREATE OR REPLACE VIEW api_v1.coverage_gap_barnefattigdom AS SELECT * FROM marts.mart_coverage_gap_barnefattigdom;
COMMENT ON VIEW api_v1.coverage_gap_barnefattigdom IS 'One row per active kommune for the latest year of SSB 08764 child
poverty data, combining the EUskala60 share (% of children in
low-income households) with the Personer count (number of
children). Backs the barnefattigdom map page (atlas-frontend
/coverage-gap/barnefattigdom).

First member of the mart_coverage_gap_<topic> family. Future
coverage-gap maps follow the same shape: latest year per kommune,
one row per kommune, value(s) pivoted out of contents_code into
named columns. PostgREST projects this view as a single endpoint;
consumers don''t filter, they read the whole map dataset in one
request.

Inactive kommuner are excluded so the map renders today''s
kommune set. NULL values are kept in place — Map.tsx renders
them as "no data".';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner are included. Unique within this view.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.kommune_name IS 'Joined from fact_kommune_indicators (originally from dim_kommune).';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.fylke_name IS 'Joined from fact_kommune_indicators (originally from
dim_fylke). NULL for kommuner whose fylke_nr isn''t in
dim_fylke (rare — Svalbard 21xx).';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.year IS 'The latest year for ssb-08764/EUskala60. Same value across all
rows; carried on each row so the consumer reads it without a
separate query.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.value_pct IS 'EU-skala 60 % share — the percent of children under 18 in
low-income households (defined as < 60 % of national median
equivalised income). NULL when upstream suppressed the cell.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.personer IS 'Number of children under 18 in low-income households at the
same year. NULL when upstream suppressed the cell.';

-- distrikt_summary  ←  marts.mart_distrikt_summary
CREATE OR REPLACE VIEW api_v1.distrikt_summary AS SELECT * FROM marts.mart_distrikt_summary;
COMMENT ON VIEW api_v1.distrikt_summary IS 'One row per regional chapter (Red Cross "distrikt" level, and the
equivalent regional tier for any other NGO with a hierarchy).
Each row carries denormalised counts of how many child chapters
the distrikt has and how many distinct kommuner those children
cover. Backs atlas-frontend /ngo/[slug]/distrikter and the
individual /distrikt/[id] pages; equivalent to the listDistrikter()
inline query.

Counts come from dim_chapter joined back to itself by
parent_chapter_id, filtered to active children. PostgREST
consumers filter via ?ngo_orgnr=eq.X (or ?chapter_id=eq.Y for the
single-distrikt case).';
COMMENT ON COLUMN api_v1.distrikt_summary.chapter_id IS 'Composite slug for the regional chapter (e.g.
''redcross-oslo''). Stable across refreshes. Unique within this
view.';
COMMENT ON COLUMN api_v1.distrikt_summary.name IS 'Display name for the regional chapter (e.g. ''Oslo Røde Kors'').';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_nr IS '4-digit kommune code where the regional chapter is
headquartered. NULL for distrikter without a single HQ
kommune. Note: kommune_coverage_count tells you how many
*child* kommuner the distrikt covers — that''s the operational
footprint, not where the office sits.';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_name IS 'Joined from dim_kommune. NULL when kommune_nr is NULL.';
COMMENT ON COLUMN api_v1.distrikt_summary.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO this distrikt belongs to.';
COMMENT ON COLUMN api_v1.distrikt_summary.child_count IS 'Count of active local chapters whose parent_chapter_id equals
this distrikt''s chapter_id. The "lokalforeninger" total shown
in the UI.';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_coverage_count IS 'Count of distinct kommuner served by this distrikt''s active
children (kommune_nr IS NOT NULL). The operational footprint;
may be smaller than child_count when multiple children share
a kommune.';

-- indicator_latest_values  ←  marts.mart_indicator_latest_values
CREATE OR REPLACE VIEW api_v1.indicator_latest_values AS SELECT * FROM marts.mart_indicator_latest_values;
COMMENT ON VIEW api_v1.indicator_latest_values IS 'One row per (source_id, contents_code, kommune_nr) at each
indicator''s latest_year, restricted to active kommuner. Backs the
data explorer''s per-indicator detail page (atlas-frontend
/data/[source_id]/[contents_code]) and is the equivalent of the
loadIndicatorValues() inline query.

PostgREST consumers filter via
?source_id=eq.X&contents_code=eq.Y. The full table is the
cross-product of every indicator with every active kommune that
has a row at latest_year, so the unfiltered row count is large
(~360 active kommuner × ~70 indicators in v1).

Inactive kommuner (kommune_is_active = false) are excluded so the
output reflects today''s kommune set, not historical codes that
upstream still emits.';
COMMENT ON COLUMN api_v1.indicator_latest_values.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''. Joins back to
fact_kommune_indicators.source_id.';
COMMENT ON COLUMN api_v1.indicator_latest_values.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde''). Combined with source_id and
kommune_nr forms the natural key of this view.';
COMMENT ON COLUMN api_v1.indicator_latest_values.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner are included.';
COMMENT ON COLUMN api_v1.indicator_latest_values.kommune_name IS 'Joined from fact_kommune_indicators (originally from dim_kommune).';
COMMENT ON COLUMN api_v1.indicator_latest_values.fylke_name IS 'Joined from fact_kommune_indicators (originally from
dim_fylke). NULL when the kommune''s fylke_nr isn''t present in
dim_fylke (rare — happens for codes like Svalbard 21xx).';
COMMENT ON COLUMN api_v1.indicator_latest_values.value IS 'Numeric value at latest_year. Unit depends on (source_id,
contents_code) — see the source''s README. NULL when upstream
suppressed the cell.';
COMMENT ON COLUMN api_v1.indicator_latest_values.status IS 'SSB suppression marker (e.g. '':'' for ''not available''). NULL
when value is present.';
COMMENT ON COLUMN api_v1.indicator_latest_values.year IS 'The latest year for this (source_id, contents_code). Repeats
across all kommuner for a given indicator — kept on the row so
PostgREST consumers can read it without a separate join.';

-- indicator_missing_kommuner  ←  marts.mart_indicator_missing_kommuner
CREATE OR REPLACE VIEW api_v1.indicator_missing_kommuner AS SELECT * FROM marts.mart_indicator_missing_kommuner;
COMMENT ON VIEW api_v1.indicator_missing_kommuner IS 'One row per (source_id, contents_code, kommune_nr) for every
active kommune that has *no* non-NULL value at the indicator''s
latest_year. The "coverage gap" sidebar on the data explorer
detail page; equivalent to the listMissingKommuner() inline query.

PostgREST consumers filter via
?source_id=eq.X&contents_code=eq.Y. Membership semantics: a
kommune is considered "missing" if it either has no row at
latest_year, or has a row with value IS NULL. Status markers ('':'',
''X'') do not count as a value.

The full table is the cross-product of every indicator with every
active kommune that lacks data. Most cells are present, so the
unfiltered row count is the per-indicator gap-list aggregated
across all indicators.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde'').';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner with no value at latest_year are listed.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.kommune_name IS 'Joined from dim_kommune.';

-- indicator_summary  ←  marts.mart_indicator_summary
CREATE OR REPLACE VIEW api_v1.indicator_summary AS SELECT * FROM marts.mart_indicator_summary;
COMMENT ON VIEW api_v1.indicator_summary IS 'One row per (source_id, contents_code) summarising the latest-year
coverage and value range for every indicator in
fact_kommune_indicators. This is the backing dataset for the data
explorer index page (atlas-frontend /data) and is the equivalent of
the listIndicators() inline query that PostgREST projects as
/mart_indicator_summary on the public API.

Query shape: latest-year-per-indicator + group-by + value/null counts
filtered to active kommuner only. Inactive kommuner (historical
codes retained by upstream) are excluded from the counts so consumers
see "how many of today''s kommuner have data?" not "how many rows
exist?".

Refreshed nightly together with fact_kommune_indicators. The
upstream_updated column carries the most recent raw load timestamp
across the rows that contributed to this summary, so freshness can
be inspected per indicator without joining to raw.* sources.';
COMMENT ON COLUMN api_v1.indicator_summary.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''. Joins back to
fact_kommune_indicators.source_id and to the source declarations
in indicators/sources.yml.';
COMMENT ON COLUMN api_v1.indicator_summary.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde''). Combined with source_id forms the
natural key of this view.';
COMMENT ON COLUMN api_v1.indicator_summary.contents_label IS 'Human-readable label for contents_code, verbatim from upstream.
NULL only if every contributing row had a NULL label (rare).';
COMMENT ON COLUMN api_v1.indicator_summary.latest_year IS 'Most recent calendar year for which this (source_id,
contents_code) has any rows in fact_kommune_indicators. The
coverage and value-range columns below are computed against
this year only.';
COMMENT ON COLUMN api_v1.indicator_summary.kommuner_with_value IS 'Count of active kommuner (kommune_is_active = true) that have a
non-NULL value for this indicator at latest_year. The headline
coverage number on the data explorer.';
COMMENT ON COLUMN api_v1.indicator_summary.kommuner_with_null IS 'Count of active kommuner that have a row at latest_year but
value IS NULL (i.e. upstream suppressed the cell). Inactive
kommuner are not counted.';
COMMENT ON COLUMN api_v1.indicator_summary.min_value IS 'Minimum non-NULL value across all rows at latest_year, regardless
of whether the kommune is active. NULL if no row had a value.';
COMMENT ON COLUMN api_v1.indicator_summary.max_value IS 'Maximum non-NULL value across all rows at latest_year, regardless
of whether the kommune is active. NULL if no row had a value.';
COMMENT ON COLUMN api_v1.indicator_summary.upstream_updated IS 'Most recent fact_kommune_indicators.updated_at across the rows
that contributed to this summary. Useful for staleness checks
per indicator without joining to raw.*.';

-- kommune_local_chapters  ←  marts.mart_kommune_local_chapters
CREATE OR REPLACE VIEW api_v1.kommune_local_chapters AS SELECT * FROM marts.mart_kommune_local_chapters;
COMMENT ON VIEW api_v1.kommune_local_chapters IS 'Active local chapters in each kommune, decorated with the NGO
name/brand and the service-category labels offered. Backs the
kommune detail page (atlas-frontend /kommuner/[kommune_nr]);
equivalent to listChaptersInKommune().

**Important:** this view returns *multiple rows per chapter* —
one per service category the chapter offers. A chapter that
provides three service categories appears as three rows for the
same kommune_nr / chapter_id, with different
service_category_code values. Consumers that want unique chapters
should distinct on chapter_id (or aggregate service categories
into an array client-side).

PostgREST consumers filter via ?kommune_nr=eq.X. Inactive
chapters, non-local chapters (regional, national), and chapters
with NULL kommune_nr are excluded. Svalbard (kommune_nr 2100,
Longyearbyen Røde Kors) is included even though 2100 isn''t in
dim_kommune — the FK relationships test is `warn`-severity to
keep this row visible.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.kommune_nr IS '4-digit kommune code where the local chapter operates. FK to
dim_kommune. The primary filter dimension for this view.
Chapters with NULL kommune_nr are excluded by the view (this
isn''t "local chapters in a kommune" if there''s no kommune).
The relationships test is `warn`-severity because Svalbard
(2100) is a real Red Cross local chapter location whose
kommune code isn''t in dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.chapter_id IS 'Composite slug for the local chapter (e.g.
''redcross-oslo-grunerløkka''). Repeats across rows when the
chapter offers multiple service categories.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.name IS 'Display name for the local chapter.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO that owns the chapter.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_name IS 'Joined from dim_ngo (legal name).';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_brand_name IS 'Joined from dim_ngo (brand name when distinct from legal
name). NULL when the NGO doesn''t use a brand alias.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.service_category_code IS 'ICNPO-derived service category code for one of the activities
this chapter offers. Combined with chapter_id forms the
natural key of this view (rows are unique on
(chapter_id, service_category_code)).';
COMMENT ON COLUMN api_v1.kommune_local_chapters.service_category_label_no IS 'Human-readable Norwegian label for service_category_code,
joined from ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.sort_order IS 'Display order from ref_atlas_service_category. Used by the UI
to render service categories in a consistent sequence; carry
on the row so consumers can sort without a separate query.';

-- meta_dimensions  ←  marts.mart_meta_dimensions
CREATE OR REPLACE VIEW api_v1.meta_dimensions AS SELECT * FROM marts.mart_meta_dimensions;
COMMENT ON VIEW api_v1.meta_dimensions IS 'Per-source × per-dimension catalogue. Backs the "what does this
column mean" panel on `/data/sources/[source_id]` (customer
frontend, PLAN-007 phase 4) and exposes editorial semantics
shoppers would otherwise have to leave Atlas to find on the
upstream''s docs site.

v1 scope (this PR): editorial pass-through over the
`_sources_dimensions` seed (4 columns: `meaning`, `value_format`,
`notes`). The `cardinality`, `example_values`, and `null_count`
columns from PLAN-007 phase 3.4''s full spec require introspecting
`raw.<source>` tables with per-source column-name rules — deferred
to a follow-up PR. See `mart_meta_dimensions.sql` header for the
open question (Jinja loop vs separate Python extract script vs
per-source `column_name:` field in manifest.yml).

Row count = same as `_sources_dimensions` (~216, growing with
every new source × upstream-dimension).';
COMMENT ON COLUMN api_v1.meta_dimensions.source_id IS 'Source the dimension belongs to. Joins to
`mart_meta_sources.source_id` and `_sources_manifest.source_id`.';
COMMENT ON COLUMN api_v1.meta_dimensions.code IS 'Upstream''s own dimension code (e.g. `Region`, `Tid`,
`ContentsCode` for SSB; `GEO`, `AAR`, `KJONN`, `MEASURE_TYPE`
for FHI). Verbatim from the source''s API/export — not
translated to canonical Atlas vocabulary.';
COMMENT ON COLUMN api_v1.meta_dimensions.meaning IS 'Short human-readable description of what the dimension
represents. Hand-authored editorial content from each source''s
`manifest.yml` `dimensions:` block.';
COMMENT ON COLUMN api_v1.meta_dimensions.value_format IS 'Encoding of values within the dimension (e.g. "4-digit year as
text", "1- to 6-character numeric code"). Empty string when no
specific format applies.';
COMMENT ON COLUMN api_v1.meta_dimensions.notes IS 'Editorial notes — code-list size, semantic gotchas, downstream
filtering decisions. Empty string when no notes apply.';

-- meta_endpoints  ←  marts.mart_meta_endpoints
CREATE OR REPLACE VIEW api_v1.meta_endpoints AS SELECT * FROM marts.mart_meta_endpoints;
COMMENT ON VIEW api_v1.meta_endpoints IS 'One row per queryable Atlas endpoint, with tags inherited from
upstream sources via the lineage graph and a `layer:<schema>` tag
from the schema. Wraps to `api_v1.meta_endpoints` and backs the
tag-filter catalogue at `/data` in the customer frontend
(PLAN-007 phase 4).

Includes endpoints from `api_v1.*`, `marts.*`, and `raw.*`
(Atlas''s three open-by-default schemas; `private_marts.*` stays
auth-gated and is excluded). Skips internal seeds prefixed `_`
(`_sources_manifest`, `_sources_dimensions`) and any `dbt_*`
diagnostic tables.

Tag inheritance uses the **union** rule: a `mart_*` derived from
many sources picks up every source''s `provider:`, `topic:`,
`geo:`, `cadence:`, and `eu_theme:` tag, deduped. Filter
"involves something annual" beats "purely annual" — see PLAN-007
phase 3.2 for the design rationale.';
COMMENT ON COLUMN api_v1.meta_endpoints.endpoint IS 'Schema-qualified table/view identifier (`<schema>.<table>`).
Primary key.';
COMMENT ON COLUMN api_v1.meta_endpoints.schema_name IS 'One of `api_v1`, `marts`, `raw`.';
COMMENT ON COLUMN api_v1.meta_endpoints.table_name IS 'Bare table/view name without schema qualification.';
COMMENT ON COLUMN api_v1.meta_endpoints.tags IS '`text[]` carrying the layer tag (`layer:<schema>`) plus inherited
source tags via union semantics. Filter via PostgREST''s
`?tags=cs.{...}` array-contains operator.';
COMMENT ON COLUMN api_v1.meta_endpoints.is_public_api IS '`true` when `schema_name = ''api_v1''`. Lets clients distinguish
stable-contract endpoints from the broader `marts.*` / `raw.*`
surfaces that are queryable but not version-guaranteed.';
COMMENT ON COLUMN api_v1.meta_endpoints.table_type IS '`BASE TABLE` for tables (most `marts.*`, all `raw.*`) and
`VIEW` for views (all `api_v1.*` wrappers). Useful for
distinguishing materialised marts from auto-wrapped views.';

-- meta_sources  ←  marts.mart_meta_sources
CREATE OR REPLACE VIEW api_v1.meta_sources AS SELECT * FROM marts.mart_meta_sources;
COMMENT ON VIEW api_v1.meta_sources IS 'Per-source catalogue row — one per ingest source in
`_sources_manifest`, joined to `raw.ingest_runs` aggregates so
consumers see freshness alongside the static metadata. Wraps to
`api_v1.meta_sources` and backs `/data/sources` in the customer
frontend (PLAN-007 phase 4).

Tags column is a Postgres `text[]` carrying the four declared
namespaces (`provider:`, `topic:`, `geo:`, `cadence:`) plus the
`eu_theme:` namespace. The customer frontend renders each as a
filter pill; PostgREST consumers filter via `?tags=cs.{provider:ssb}`.

`last_ingested_at` and `last_upstream_update_at` come from
`raw.ingest_runs` aggregated over successful (`exit_code = 0`)
runs. Sources whose ingest module hasn''t yet captured the
upstream''s "updated" field leave `last_upstream_update_at` NULL —
that''s the design (`raw.ingest_runs.upstream_updated_at` is
nullable per migration 028).

`downstream_model_count` is the number of distinct dbt models
that derive from this source via the `lineage` seed (Phase 3.3).
0 for sources whose data hasn''t yet been wired into a mart.';
COMMENT ON COLUMN api_v1.meta_sources.source_id IS 'Atlas catalogue id; primary key. Matches `_sources_manifest.source_id`.';
COMMENT ON COLUMN api_v1.meta_sources.upstream_id IS 'Upstream''s own identifier (SSB table number, FHI dataset slug, etc.).';
COMMENT ON COLUMN api_v1.meta_sources.upstream_url IS 'Canonical link to the data on the upstream''s site (often the API endpoint).';
COMMENT ON COLUMN api_v1.meta_sources.upstream_landing_page IS 'Human-browsable web page describing the dataset (DCAT-AP `dcat:landingPage`).
Empty when `upstream_url` is already browsable; clients fall back to that.';
COMMENT ON COLUMN api_v1.meta_sources.upstream_title IS 'Source''s authoritative title at the upstream (usually Norwegian).';
COMMENT ON COLUMN api_v1.meta_sources.description IS 'One-paragraph framing for the customer-facing catalogue.';
COMMENT ON COLUMN api_v1.meta_sources.publisher IS 'Institution that publishes the data.';
COMMENT ON COLUMN api_v1.meta_sources.license IS 'License token (e.g. `NLOD`); see `license_url` for terms.';
COMMENT ON COLUMN api_v1.meta_sources.license_url IS 'URL of the license terms.';
COMMENT ON COLUMN api_v1.meta_sources.periodicity IS 'Update cadence as ISO 8601 (`P1Y` / `P3M` / `P1M` / `P1D`)
or `irregular`. More precise than the `cadence:` tag.';
COMMENT ON COLUMN api_v1.meta_sources.eu_theme IS 'EU Publications Office Data Theme code (one of 13: `AGRI`, `ECON`,
`EDUC`, `ENER`, `ENVI`, `GOVE`, `HEAL`, `INTR`, `JUST`, `REGI`,
`SOCI`, `TECH`, `TRAN`). Aligns with Felles datakatalog / DCAT-AP.';
COMMENT ON COLUMN api_v1.meta_sources.attribution IS 'Citation string for academic / legal compliance (e.g.
"Kilde: Statistisk sentralbyrå, tabell 08764").';
COMMENT ON COLUMN api_v1.meta_sources.tags IS '`text[]` of namespaced tags: `provider:<X>`, `topic:<X>`,
`geo:<X>`, `cadence:<X>`, `eu_theme:<X>`. Filter via PostgREST''s
`?tags=cs.{...}` array-contains operator. Always 5 entries (one
per declared namespace).';
COMMENT ON COLUMN api_v1.meta_sources.last_ingested_at IS '`MAX(finished_at)` from `raw.ingest_runs` filtered to
successful runs (`exit_code = 0`). NULL until the source has
at least one successful run on the current cluster.';
COMMENT ON COLUMN api_v1.meta_sources.last_upstream_update_at IS '`MAX(upstream_updated_at)` from successful ingest runs.
NULL when the source hasn''t run yet OR its ingest module
doesn''t capture the upstream''s "updated" field (Red Cross
web scrape, Brreg per-entity fetch).';
COMMENT ON COLUMN api_v1.meta_sources.latest_row_count IS '`rows_parsed` from the most recent successful run. NULL when
the source has zero successful runs on the current cluster.';
COMMENT ON COLUMN api_v1.meta_sources.total_runs IS 'Count of successful runs ever recorded for this source. 0 when
no successful run exists.';
COMMENT ON COLUMN api_v1.meta_sources.downstream_model_count IS 'Number of distinct downstream dbt models that derive from this
source via the `lineage` seed. 0 for sources not yet wired
into a mart.';

-- ngo_index  ←  marts.mart_ngo_index
CREATE OR REPLACE VIEW api_v1.ngo_index AS SELECT * FROM marts.mart_ngo_index;
COMMENT ON VIEW api_v1.ngo_index IS 'One row per NGO in dim_ngo with chapter_count and has_supply
decorations. Backs the NGO landing page (atlas-frontend /ngo) and
is equivalent to the listNgos() inline query.

chapter_count counts only active chapters (dim_chapter.is_active),
so a defunct NGO sits at 0 even if its historical chapters are
retained. has_supply is the convenience boolean (chapter_count > 0).
The full table is small (~11 rows in v1, growing as new NGOs
land), so PostgREST consumers typically read all of it.';
COMMENT ON COLUMN api_v1.ngo_index.orgnr IS '9-digit Brreg organisasjonsnummer (text — leading zeros are
preserved). Natural key for this view.';
COMMENT ON COLUMN api_v1.ngo_index.slug IS 'kebab-case URL-friendly identifier (e.g. ''redcross'', ''kirkens-bymisjon'').';
COMMENT ON COLUMN api_v1.ngo_index.name IS 'Legal name from Brreg.';
COMMENT ON COLUMN api_v1.ngo_index.brand_name IS 'Common brand name when distinct from legal name (e.g.
''Sanitetskvinnene'' vs N.K.S.). NULL when the brand equals
the legal name.';
COMMENT ON COLUMN api_v1.ngo_index.website_url IS 'NGO''s primary website. Used as the outbound link from the index page.';
COMMENT ON COLUMN api_v1.ngo_index.tier IS 'Structural-fit tier (A / B / C) from
docs/research/ngo-landscape.md. v1 includes Tier A only.';
COMMENT ON COLUMN api_v1.ngo_index.chapter_data_shape IS 'How this NGO models its chapters. Values: ''distrikt+local''
(Red Cross), ''flat'' (single-tier), ''none'' (no chapters).
Drives which supply staging model the NGO uses.';
COMMENT ON COLUMN api_v1.ngo_index.has_chapters IS 'True when the NGO has any chapters at all (regardless of activity).';
COMMENT ON COLUMN api_v1.ngo_index.primary_focus IS 'One-line description of the NGO''s main mission area.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_1 IS 'ICNPO classification code (primary). See ref_icnpo. NULL when
unclassified.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_2 IS 'ICNPO classification code (secondary). NULL when not used.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_3 IS 'ICNPO classification code (tertiary). NULL when not used.';
COMMENT ON COLUMN api_v1.ngo_index.chapter_count IS 'Count of active chapters for this NGO (filtered by
dim_chapter.is_active = true). Zero if the NGO has no chapters
or all chapters are dormant.';
COMMENT ON COLUMN api_v1.ngo_index.has_supply IS 'Convenience boolean: chapter_count > 0. True when the NGO has
at least one active chapter — i.e. it appears on the supply
side of Atlas.';

-- ngo_overview  ←  marts.mart_ngo_overview
CREATE OR REPLACE VIEW api_v1.ngo_overview AS SELECT * FROM marts.mart_ngo_overview;
COMMENT ON VIEW api_v1.ngo_overview IS 'One row per NGO in dim_ngo with the six count metrics shown on
the per-NGO landing page (atlas-frontend /ngo/[slug]).
Equivalent to the getNgoOverview() inline query, but precomputed
for all NGOs so PostgREST projects it as a single endpoint
consumers filter via ?orgnr=eq.X.

Counts include both active and inactive chapters in the
level-specific buckets (national/regional/local). kommune_count
counts distinct kommune_nr only across *active* local chapters,
matching the original query''s behaviour.';
COMMENT ON COLUMN api_v1.ngo_overview.orgnr IS '9-digit Brreg organisasjonsnummer. Natural key for this view.';
COMMENT ON COLUMN api_v1.ngo_overview.chapter_count IS 'Total count of chapters for this NGO across all levels (active + inactive).';
COMMENT ON COLUMN api_v1.ngo_overview.national_count IS 'Count of chapters at chapter_level = ''national''.';
COMMENT ON COLUMN api_v1.ngo_overview.regional_count IS 'Count of chapters at chapter_level = ''regional'' (e.g. Red Cross distrikt).';
COMMENT ON COLUMN api_v1.ngo_overview.local_count IS 'Count of chapters at chapter_level = ''local'' (the kommune-bound branches).';
COMMENT ON COLUMN api_v1.ngo_overview.activity_count IS 'Count of distinct activities offered by this NGO (rows in
dim_activity for this orgnr).';
COMMENT ON COLUMN api_v1.ngo_overview.kommune_count IS 'Count of distinct kommuner with at least one active local
chapter for this NGO. The "footprint" metric for coverage-gap
questions.';

-- Grant SELECT to the per-app anon role if it exists (created by UIS's
-- ./uis configure postgrest --app atlas). Guarded so this migration
-- applies cleanly against environments where UIS hasn't run configure yet.
DO $$ BEGIN
  IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'atlas_web_anon') THEN
    GRANT USAGE ON SCHEMA api_v1 TO atlas_web_anon;
    GRANT SELECT ON ALL TABLES IN SCHEMA api_v1 TO atlas_web_anon;
    ALTER DEFAULT PRIVILEGES IN SCHEMA api_v1
      GRANT SELECT ON TABLES TO atlas_web_anon;
  END IF;
END $$;

-- Tell PostgREST to reload its schema cache so newly-added or removed
-- views surface immediately. No-op if no PostgREST is listening.
NOTIFY pgrst, 'reload schema';
