-- atlas-data/dbt/api_v1_generated.sql
-- AUTO-GENERATED by atlas-data/dbt/scripts/generate_api_v1.py — do not hand-edit.
-- Re-running ./regenerate-api-v1.sh after a dbt-model change is the source of truth.
--
-- Apply via ./apply-api-v1.sh AFTER `dbt run` — the wrappers reference
-- marts.mart_* tables which only exist after dbt has built them.
-- All statements are idempotent (CREATE OR REPLACE / IF NOT EXISTS / DROP IF EXISTS).
--
-- For design rationale see:
--   website/docs/ai-developer/plans/active/PLAN-004-postgrest-api-v1-wrapper.md
--
-- ROLLBACK: undeploy + purge UIS first (./uis undeploy postgrest --app atlas
-- + ./uis configure postgrest --app atlas --purge), then DROP SCHEMA api_v1 CASCADE.

CREATE SCHEMA IF NOT EXISTS api_v1;

COMMENT ON SCHEMA api_v1 IS
  'Atlas — open semantic layer over Norwegian public data

Curated wrapper views over Norwegian public data and NGO supply data, served
by PostgREST. Values are republished as the upstream publishes them.

THE CATALOGUE — start here:
  meta_endpoints    every relation below, with tags. The index.
  meta_sources      one row per ingested source: licence, publisher,
                    coverage, freshness, downstream model count.
  meta_dimensions   one row per source x upstream dimension: what that coded
                    column MEANS and its value format. Read it before
                    interpreting a code, and before deriving a fact about a
                    dimension from prose.

INDICATORS — municipal figures from SSB, FHI and Bufdir:
  indicator_summary            one row per (source, measure): latest year,
                               coverage, value range.
  indicator_latest_values      per-kommune values at the latest year.
  indicator_missing_kommuner   which kommuner an indicator does NOT cover.
  coverage_gap_barnefattigdom  the same question for child poverty.
  unattributed_totals          the remainder belonging to no kommune, so
                               totals reconcile.
  kommune_befolkning_alder     population by age band and sex.
  bufdir_indicator_alias       Bufdir indicator naming.

SUPPLY — voluntary-sector presence:
  ngo_index, ngo_overview      organisations and their summary.
  activity_catalog             what each organisation does.
  kommune_ngo_summary          per-kommune rollup.
  kommune_ngo_totals           national totals; reconcile these against
                               unattributed_totals.
  distrikt_summary             chapters by district.
  kommune_local_chapters       chapters resolved to a kommune.

REFERENCE:
  dim_kommune                  the municipality dimension. Keeps SSB''s 9999
                               ''Uoppgitt'' because Klass 131 publishes it; the
                               analytical relations exclude it.
  brreg_enhet                  the Bronnoysund register mirror.

TIME IS THE DIMENSION MOST OFTEN MISREAD. A year here can be the FIRST year
of a multi-year window. indicator_summary.latest_year pairs with
latest_year_window_years, and indicator_latest_values.year with window_years;
the span is year .. year + window_years - 1. meta_dimensions carries the
upstream''s own words for the same fact.';

-- activity_catalog  ←  marts.mart_activity_catalog
CREATE OR REPLACE VIEW api_v1.activity_catalog AS SELECT * FROM marts.mart_activity_catalog;
COMMENT ON VIEW api_v1.activity_catalog IS '🔵 EXPECTED EMPTY TODAY, AND THAT IS NOT A DEFECT. Its one row per (NGO, activity), so it is empty until Red Cross activity data is loaded.
Terje''s position, 2026-09-21: the Red Cross data is not coming now, it
will be there later. The relation is published and answers so a consumer
can build against its shape before the rows arrive.

⚠️ A consumer cannot tell "empty by design" from "broken" without being
told, and two of these three were asked about on the day someone noticed
(urb-agents #1351). If this relation is still empty and this note is
gone, something regressed.

One row per (NGO, activity) joining dim_activity to the
service-category seed for the human-readable label, plus a count
of active chapters offering each activity. Backs the per-NGO
activity catalogue page (atlas-frontend
/ngo/[slug]/aktiviteter); equivalent to listActivities().

The full table is small (~35 rows for Red Cross alone in v1) and
grows as new NGOs land. PostgREST consumers filter via
?ngo_orgnr=eq.X.';
COMMENT ON COLUMN api_v1.activity_catalog.activity_id IS 'Composite slug (e.g. ''redcross-besokstjeneste''). Stable across
refreshes. Unique within this view.';
COMMENT ON COLUMN api_v1.activity_catalog.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO offering the activity.';
COMMENT ON COLUMN api_v1.activity_catalog.canonical_name IS 'Atlas''s canonical Norwegian name for the activity.';
COMMENT ON COLUMN api_v1.activity_catalog.service_category_code IS 'ICNPO-derived service category code (e.g. ''health'',
''social-services''). FK to ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.activity_catalog.service_category_label_no IS 'Human-readable Norwegian label for service_category_code,
joined from ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.activity_catalog.is_active IS 'Whether this activity is still offered by the NGO. Inactive
activities are kept so historical analysis can still resolve
activity_id values.';
COMMENT ON COLUMN api_v1.activity_catalog.chapter_count IS 'Count of distinct active chapters offering this activity. Zero
when the activity exists in dim_activity but no active chapter
provides it (rare but possible during transitions).';

-- brreg_enhet  ←  marts.mart_brreg_enhet
CREATE OR REPLACE VIEW api_v1.brreg_enhet AS SELECT * FROM marts.mart_brreg_enhet;
COMMENT ON VIEW api_v1.brreg_enhet IS 'Every organisation registered in Norway — the whole of Brønnøysundregistrene''s
Enhetsregisteret, around 1.17 million rows, current as of the last change-feed run.
Companies, foundations, associations, public bodies and sole proprietorships.

Kilde: Brønnøysundregistrene. Inneholder data under norsk lisens for offentlige data
(NLOD) tilgjengeliggjort av Brønnøysundregistrene — https://data.norge.no/nlod/no/2.0.
Re-users must carry this attribution onward; it is a condition of the licence, not a
courtesy.

Deleted organisations are excluded. Brreg reports deletions through its change feed and
Atlas applies them, so an organisation removed upstream disappears from here — but the
version history is kept, so what it looked like before removal remains answerable.

Completeness caveat: this reflects deletions Brreg REPORTS. A row Atlas holds that Brreg
never had would not be removed by any automatic path, because no change event would ever
mention it.';
COMMENT ON COLUMN api_v1.brreg_enhet.organisasjonsnummer IS 'Nine-digit Norwegian organisation number. Text, never a number — leading zeros are significant. Stable for the life of the organisation, and the join key for organisational data from any Norwegian source.';
COMMENT ON COLUMN api_v1.brreg_enhet.navn IS 'Registered name, verbatim from Brreg. For an enkeltpersonforetak (organisasjonsform ENK) this is very often the proprietor''s own personal name, because that is how the register records them.';
COMMENT ON COLUMN api_v1.brreg_enhet.organisasjonsform_kode IS 'Legal form code — AS (aksjeselskap), ENK (enkeltpersonforetak), FLI (forening/lag/innretning), STI (stiftelse) and others. The usual filter for separating companies from associations, or for excluding sole proprietorships.';
COMMENT ON COLUMN api_v1.brreg_enhet.organisasjonsform_beskrivelse IS 'Human-readable Norwegian label for organisasjonsform_kode, as Brreg publishes it.';
COMMENT ON COLUMN api_v1.brreg_enhet.naeringskode1_kode IS 'Primary NACE industry code (SN2007), e.g. 94.992. Null for roughly 2% of the register.';
COMMENT ON COLUMN api_v1.brreg_enhet.kommune_nr IS 'Kommune code of the registered business address. For an enkeltpersonforetak the registered business address is commonly the proprietor''s home address. Null where no business address is registered (~6%). Some codes are historical or pseudo-regions and will not resolve against a current kommune list.';
COMMENT ON COLUMN api_v1.brreg_enhet.antall_ansatte IS 'Registered employee count. NULL MEANS "NOT REPORTED", NOT ZERO — the field is present on only ~4% of records. Use har_registrert_antall_ansatte to distinguish the two; reading NULL as 0 understates staffed organisations badly.';
COMMENT ON COLUMN api_v1.brreg_enhet.har_registrert_antall_ansatte IS 'Whether Brreg holds a registered employee count at all. Present on 100% of records, and the only way to tell "zero employees" from "no figure reported".';
COMMENT ON COLUMN api_v1.brreg_enhet.konkurs IS 'Whether the organisation is in bankruptcy proceedings. Straight from Brreg.';
COMMENT ON COLUMN api_v1.brreg_enhet.under_avvikling IS 'Whether the organisation is being wound up voluntarily. Straight from Brreg.';
COMMENT ON COLUMN api_v1.brreg_enhet.under_tvangsavvikling IS 'Whether the organisation is under compulsory winding-up or dissolution.';
COMMENT ON COLUMN api_v1.brreg_enhet.is_active IS 'Convenience boolean — true when none of konkurs, under_avvikling or under_tvangsavvikling is set. Means "trading", not "exists": all three states are still registered organisations. Ignore this column if you want everything registered.';
COMMENT ON COLUMN api_v1.brreg_enhet.registrert_i_frivillighetsregisteret IS 'Whether the organisation is in Frivillighetsregisteret, the voluntary-organisation register — true for roughly 72,800 records. This is what makes the Norwegian voluntary sector discoverable as a population rather than a curated list.';
COMMENT ON COLUMN api_v1.brreg_enhet.registrert_dato IS 'Date the organisation was entered in Enhetsregisteret.';
COMMENT ON COLUMN api_v1.brreg_enhet.icnpo_nummer IS 'Primary ICNPO code as the organisation classified itself in Frivillighetsregisteret, e.g. "9100". Null for organisations not in that register, and for members declaring none. Null does not mean "not voluntary" — use registrert_i_frivillighetsregisteret for that.';
COMMENT ON COLUMN api_v1.brreg_enhet.icnpo_kategori IS 'Primary ICNPO category label paired with icnpo_nummer.';
COMMENT ON COLUMN api_v1.brreg_enhet.grasrotandel_deltar_i IS 'Whether the organisation participates in Grasrotandelen, Norsk Tipping''s grassroots funding scheme. Null for organisations not in Frivillighetsregisteret.';
COMMENT ON COLUMN api_v1.brreg_enhet.frivillig_innfoert_dato IS 'Date of entry in Frivillighetsregisteret — distinct from registrert_dato, which is the Enhetsregisteret entry. Organisations often exist for years before registering as voluntary.';
COMMENT ON COLUMN api_v1.brreg_enhet.last_seen_at IS 'When the INGEST last wrote this row into Atlas''s raw layer, from either the bulk snapshot or a change-feed run. Tracks Atlas''s load, not an upstream event. Read it together with reconciled_at — this is the ingest clock, that is the transform clock.';
COMMENT ON COLUMN api_v1.brreg_enhet.reconciled_at IS 'When the TRANSFORM last reconciled this row into the served layer. 🔴 Read both clocks: the change feed polls every half hour and this reconciliation follows ten minutes behind it, so the data behind this endpoint can be older than what Atlas has already ingested. Without both, "current" means different things depending on which table you read — an install once sat 13.5 hours behind Brreg with every health check green. ⚠️ Only organisations that actually changed are re-stamped, so an old value means "nothing about this organisation has changed since then", not "this endpoint is stale".';
COMMENT ON COLUMN api_v1.brreg_enhet.doc IS 'The complete upstream record as Brreg published it, with nothing dropped or renamed — including postal and business addresses, telephone, mobile, email, website, capital, institutional sector code, articles of association and historical names. Responses are large: a document averages ~1.7 kB, so select the typed columns instead unless you need a field this view does not surface.';

-- bufdir_indicator_alias  ←  marts.mart_bufdir_indicator_alias
CREATE OR REPLACE VIEW api_v1.bufdir_indicator_alias AS SELECT * FROM marts.mart_bufdir_indicator_alias;
COMMENT ON VIEW api_v1.bufdir_indicator_alias IS 'Cross-release alias table for `bufdir-barnefattigdom`
`indicator_api_id` renumbers. One row per (historical_id,
canonical_id) mapping consumers join on for cross-time-series
continuity when Bufdir splits, retires, or renumbers a workbook
upstream — e.g. the observed `Indikator 9` → `9a` / `9b` split,
and `Indikator 10` retired without successor.

Thin republish of the editorial seed `bufdir_indicator_alias` so
the PLAN-004 generator auto-emits `api_v1.bufdir_indicator_alias`
(the leading `mart_` is stripped per `models/marts/api/README.md`
§ Naming).

See `website/docs/ai-developer/plans/active/PLAN-bufdir-surrogate-id-migration.md`
for design rationale + the maintenance ritual that appends rows
when a new Bufdir bundle release surfaces additional renumbering.';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.source_id IS 'Source the alias applies to. Always `bufdir-barnefattigdom`
today; forward-looking column kept so other ZIP sources can
adopt the same convention without a schema migration.';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.historical_id IS 'Previous `indicator_api_id` from an earlier bufdir release —
the id consumers may have cached and now need to bridge to
the current canonical id. Same shape as
`indicators__bufdir_barnefattigdom.indicator_api_id`
(`bf_zip_ind_<N>`).';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.canonical_id IS 'Current `indicator_api_id`, or NULL when the historical
indicator was retired without a successor. NULL is meaningful:
consumers treat such rows as terminating series rather than
orphans.';
COMMENT ON COLUMN api_v1.bufdir_indicator_alias.note IS 'Editorial explanation of the renumbering event — why the
historical id maps to this canonical id, or why no successor
exists. One sentence; read by humans, not parsers.';

-- coverage_gap_barnefattigdom  ←  marts.mart_coverage_gap_barnefattigdom
CREATE OR REPLACE VIEW api_v1.coverage_gap_barnefattigdom AS SELECT * FROM marts.mart_coverage_gap_barnefattigdom;
COMMENT ON VIEW api_v1.coverage_gap_barnefattigdom IS 'One row per active kommune for the latest year of SSB 08764 child
poverty data, combining the EUskala60 share (% of children in
low-income households) with the Personer count (number of
children). Backs the barnefattigdom map page (atlas-frontend
/coverage-gap/barnefattigdom).

First member of the mart_coverage_gap_<topic> family. Future
coverage-gap maps follow the same shape: latest year per kommune,
one row per kommune, value(s) pivoted out of contents_code into
named columns. PostgREST projects this view as a single endpoint;
consumers don''t filter, they read the whole map dataset in one
request.

Inactive kommuner are excluded so the map renders today''s
kommune set. NULL values are kept in place — Map.tsx renders
them as "no data".';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner are included. Unique within this view.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.kommune_name IS 'Joined from fact_kommune_indicators (originally from dim_kommune).';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.fylke_name IS 'Joined from fact_kommune_indicators (originally from
dim_fylke). NULL for kommuner whose fylke_nr isn''t in
dim_fylke (rare — Svalbard 21xx).';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.year IS 'The latest year for ssb-08764/EUskala60. Same value across all
rows; carried on each row so the consumer reads it without a
separate query.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.value_pct IS 'EU-skala 60 % share — the percent of children under 18 in
low-income households (defined as < 60 % of national median
equivalised income). NULL when upstream suppressed the cell.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.personer IS 'DENOMINATOR, NOT A COUNT OF POOR CHILDREN. Every person under
18 in the kommune that year — SSB 08764 ContentsCode
''Personer'', whose own metadata reads "Persons under 18 years
of age", unit persons.

The number of children in low-income households is
personer * value_pct / 100. It is not published as a column;
derive it.

This description said "number of children under 18 in
low-income households" until 2026-09-19, which is false by
roughly ninefold and about child poverty. A consumer building
on the published API summed the column, got 1,097,107 against
a national under-18 population of about 1.1 million, and
caught it (urb-agents #1250, #1251). Derived correctly the
same sum is 124,670, near the ~11 % national rate.

Nothing in the data contradicted the wrong reading: the
column is plausible, non-null and internally consistent, and
only summing it and recognising the total gives it away. The
view description two entries above was right the whole time,
so the contract disagreed with itself.

NULL when upstream suppressed the cell.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.barn_i_lavinntekt IS 'Children under 18 in low-income households — the number most
consumers come here for. DERIVED as
personer * value_pct / 100, rounded.

SSB does not publish this. Table 08764 carries the total and
the shares only, so every consumer has to compute it, and one
got it wrong because the `personer` description claimed to be
this column already (urb-agents #1250, #1251). Added on
Terje''s authorisation rather than renaming `personer`, so the
consumer that found the defect keeps working.

ESTIMATE, NOT A COUNT. value_pct is published to one decimal,
so the true value lies within ±0.05 % of personer: about ±65
children for Oslo, ±4 for a kommune of 7 000. Do not present
it as SSB''s own figure.

NULL when either input was suppressed upstream.';

-- dim_kommune  ←  marts.mart_dim_kommune
CREATE OR REPLACE VIEW api_v1.dim_kommune AS SELECT * FROM marts.mart_dim_kommune;
COMMENT ON VIEW api_v1.dim_kommune IS 'The canonical municipality registry — SSB Klass 131, with fylke
name joined. Published as api_v1.dim_kommune.

Fourteen references in this file already pointed at dim_kommune —
five column descriptions saying "FK to dim_kommune" and the rest
`relationships` tests — while it was not published. A consumer
building on the API found the gap and called publishing it "the
single highest-leverage small addition on this list — every
consumer is currently rebuilding it, and each of us is rebuilding
it slightly differently" (urb-agents #1250, finding 4).

Historical codes are included with is_active = false, because a
consumer joining older data needs them to resolve. Filter
?is_active=is.true for today''s 357.

Population and centroids are deliberately absent — see the model
for why; both would be wrong in a dimension rather than merely
missing.';
COMMENT ON COLUMN api_v1.dim_kommune.kommune_nr IS '4-digit zero-padded kommune code, SSB canonical form
(''0301'' = Oslo). The join key every other Atlas relation uses.';
COMMENT ON COLUMN api_v1.dim_kommune.kommune_name IS 'Kommune name in bokmål.';
COMMENT ON COLUMN api_v1.dim_kommune.kommune_name_alt IS 'The alternative official name where SSB publishes one —
in practice the Sámi variant, split out of upstream''s
"Name - Nama" string rather than left embedded in
kommune_name. NULL for most kommuner.';
COMMENT ON COLUMN api_v1.dim_kommune.fylke_nr IS '2-digit fylke code, derived from the first two digits of
kommune_nr per SSB''s long-standing convention.';
COMMENT ON COLUMN api_v1.dim_kommune.fylke_name IS 'Joined from dim_fylke. NULL where the fylke code is not in
dim_fylke — pseudo-regions and Svalbard (21xx) — rather than
dropping the kommune, so an unresolvable fylke costs a label
and not a row.';
COMMENT ON COLUMN api_v1.dim_kommune.is_active IS 'True when the CODE is current — which is not the same as "this
is a municipality". 358 rows satisfy it: 357 kommuner plus the
9999 sentinel. Combine with is_sentinel.

⚠️ Sentinel codes such as 9999 ''Uoppgitt'' are present in this
dimension and reach api_v1 views unmarked — whether they
should be excluded or flagged is an open product question
(urb-agents #700), raised again by a consumer whose first
build reported 358 kommuner and carried a null-everything row
into a chart.';
COMMENT ON COLUMN api_v1.dim_kommune.valid_from IS 'Date the code became valid. NULL where upstream gives none.';
COMMENT ON COLUMN api_v1.dim_kommune.valid_to IS 'Date the code became inactive. NULL = still active.';
COMMENT ON COLUMN api_v1.dim_kommune.notes IS 'Upstream''s own note on the code, typically recording a merger
or reorganisation. NULL for most rows.';
COMMENT ON COLUMN api_v1.dim_kommune.is_sentinel IS 'True for SSB''s 9999 ''Uoppgitt'' bucket — a current code that is
not a municipality.

⚠️ is_active does NOT exclude it. `?is_active=eq.true` returns
358, not 357, and the extra row is this one (measured on the
live API, urb-agents #1265). For real municipalities filter
`?is_sentinel=is.false`.

🔵 THIS RELATION KEEPS THE ROW ON PURPOSE, AND IT IS NOW THE
ONLY PUBLISHED ONE THAT DOES. SSB''s Klass 131 contains 9999,
and this dimension mirrors SSB''s kommune list — dropping it
would mean Atlas''s list no longer matches the source anyone
would reconcile against.

⚠️ As of 2026-09-21 the ANALYTICAL relations no longer carry
it: coverage_gap_barnefattigdom, indicator_latest_values,
indicator_missing_kommuner and kommune_ngo_summary exclude it,
and indicator_summary stopped counting it in its coverage
figures. Those are Atlas''s own constructs and their grain is
"one municipality"; this one is a mirror. Terje''s decision,
urb-agents #1301.

The unattributable value it represented is published in
`unattributed_totals`, not discarded.';

-- distrikt_summary  ←  marts.mart_distrikt_summary
CREATE OR REPLACE VIEW api_v1.distrikt_summary AS SELECT * FROM marts.mart_distrikt_summary;
COMMENT ON VIEW api_v1.distrikt_summary IS '🔵 EXPECTED EMPTY TODAY, AND THAT IS NOT A DEFECT. Its grain is Red Cross districts, so it is empty until that data is loaded.
Terje''s position, 2026-09-21: the Red Cross data is not coming now, it
will be there later. The relation is published and answers so a consumer
can build against its shape before the rows arrive.

⚠️ A consumer cannot tell "empty by design" from "broken" without being
told, and two of these three were asked about on the day someone noticed
(urb-agents #1351). If this relation is still empty and this note is
gone, something regressed.

One row per regional chapter (Red Cross "distrikt" level, and the
equivalent regional tier for any other NGO with a hierarchy).
Each row carries denormalised counts of how many child chapters
the distrikt has and how many distinct kommuner those children
cover. Backs atlas-frontend /ngo/[slug]/distrikter and the
individual /distrikt/[id] pages; equivalent to the listDistrikter()
inline query.

Counts come from dim_chapter joined back to itself by
parent_chapter_id, filtered to active children. PostgREST
consumers filter via ?ngo_orgnr=eq.X (or ?chapter_id=eq.Y for the
single-distrikt case).';
COMMENT ON COLUMN api_v1.distrikt_summary.chapter_id IS 'Composite slug for the regional chapter (e.g.
''redcross-oslo''). Stable across refreshes. Unique within this
view.';
COMMENT ON COLUMN api_v1.distrikt_summary.name IS 'Display name for the regional chapter (e.g. ''Oslo Røde Kors'').';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_nr IS '4-digit kommune code where the regional chapter is
headquartered. NULL for distrikter without a single HQ
kommune. Note: kommune_coverage_count tells you how many
*child* kommuner the distrikt covers — that''s the operational
footprint, not where the office sits.';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_name IS 'Joined from dim_kommune. NULL when kommune_nr is NULL.';
COMMENT ON COLUMN api_v1.distrikt_summary.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO this distrikt belongs to.';
COMMENT ON COLUMN api_v1.distrikt_summary.child_count IS 'Count of active local chapters whose parent_chapter_id equals
this distrikt''s chapter_id. The "lokalforeninger" total shown
in the UI.';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_coverage_count IS 'Count of distinct kommuner served by this distrikt''s active
children (kommune_nr IS NOT NULL). The operational footprint;
may be smaller than child_count when multiple children share
a kommune.';

-- indicator_latest_values  ←  marts.mart_indicator_latest_values
CREATE OR REPLACE VIEW api_v1.indicator_latest_values AS SELECT * FROM marts.mart_indicator_latest_values;
COMMENT ON VIEW api_v1.indicator_latest_values IS 'One row per (source_id, contents_code, kommune_nr) at each
indicator''s latest_year, restricted to active kommuner. Backs the
data explorer''s per-indicator detail page (atlas-frontend
/data/[source_id]/[contents_code]) and is the equivalent of the
loadIndicatorValues() inline query.

🔴 ROW COUNT IS NOT COVERAGE. A row exists for every active kommune
the source publishes at all, INCLUDING those where `value` is null.
So a series returns ~357 rows whether 357 kommuner have a number or
66 do, and counting rows overstates coverage by up to five times.

⚠️ This has always been true and became dangerous on 2026-09-21,
when nine Ungdata sources published at 18-43 % kommune coverage
against SSB register sources at nearly 100 %. `fhi-hasj` returns
357 rows carrying 66 values.

✅ `indicator_summary.kommuner_with_value` is the live count and the
only thing to trust. It is not restated here on purpose — a number
copied into a description goes stale, which is the defect that made
`fhi-depresjon` advertise fourteen years of data it never held.

PostgREST consumers filter via
?source_id=eq.X&contents_code=eq.Y. The full table is the
cross-product of every indicator with every active kommune that
has a row at latest_year, so the unfiltered row count is large
(~360 active kommuner × ~70 indicators in v1).

Inactive kommuner (kommune_is_active = false) are excluded so the
output reflects today''s kommune set, not historical codes that
upstream still emits.';
COMMENT ON COLUMN api_v1.indicator_latest_values.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''. Joins back to
fact_kommune_indicators.source_id.';
COMMENT ON COLUMN api_v1.indicator_latest_values.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde''). Combined with source_id and
kommune_nr forms the natural key of this view.';
COMMENT ON COLUMN api_v1.indicator_latest_values.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner are included.';
COMMENT ON COLUMN api_v1.indicator_latest_values.kommune_name IS 'Joined from fact_kommune_indicators (originally from dim_kommune).';
COMMENT ON COLUMN api_v1.indicator_latest_values.fylke_name IS 'Joined from fact_kommune_indicators (originally from
dim_fylke). NULL when the kommune''s fylke_nr isn''t present in
dim_fylke (rare — happens for codes like Svalbard 21xx).';
COMMENT ON COLUMN api_v1.indicator_latest_values.value IS 'Numeric value at latest_year. Unit depends on (source_id,
contents_code) — see the source''s README. NULL when upstream
suppressed the cell.';
COMMENT ON COLUMN api_v1.indicator_latest_values.status IS 'SSB suppression marker (e.g. '':'' for ''not available''). NULL
when value is present.';
COMMENT ON COLUMN api_v1.indicator_latest_values.year IS 'The latest year for this (source_id, contents_code). Repeats
across all kommuner for a given indicator — kept on the row so
PostgREST consumers can read it without a separate join.

⚠️ For a windowed source this is the FIRST year of the window.
Render it with `window_years`, never alone.';
COMMENT ON COLUMN api_v1.indicator_latest_values.window_years IS 'How many calendar years `year` covers, carried from
fact_kommune_indicators. 1 for an annual series. The span is
`year` to `year + window_years - 1` inclusive. See
`mart_indicator_summary.latest_year_window_years` for why this
is a column rather than prose.';

-- indicator_missing_kommuner  ←  marts.mart_indicator_missing_kommuner
CREATE OR REPLACE VIEW api_v1.indicator_missing_kommuner AS SELECT * FROM marts.mart_indicator_missing_kommuner;
COMMENT ON VIEW api_v1.indicator_missing_kommuner IS 'One row per (source_id, contents_code, kommune_nr) for every
active kommune that has *no* non-NULL value at the indicator''s
latest_year. The "coverage gap" sidebar on the data explorer
detail page; equivalent to the listMissingKommuner() inline query.

PostgREST consumers filter via
?source_id=eq.X&contents_code=eq.Y. Membership semantics: a
kommune is considered "missing" if it either has no row at
latest_year, or has a row with value IS NULL. Status markers ('':'',
''X'') do not count as a value.

The full table is the cross-product of every indicator with every
active kommune that lacks data. Most cells are present, so the
unfiltered row count is the per-indicator gap-list aggregated
across all indicators.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde'').';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner with no value at latest_year are listed.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.kommune_name IS 'Joined from dim_kommune.';

-- indicator_summary  ←  marts.mart_indicator_summary
CREATE OR REPLACE VIEW api_v1.indicator_summary AS SELECT * FROM marts.mart_indicator_summary;
COMMENT ON VIEW api_v1.indicator_summary IS 'One row per (source_id, contents_code) summarising the latest-year
coverage and value range for every indicator in
fact_kommune_indicators. This is the backing dataset for the data
explorer index page (atlas-frontend /data) and is the equivalent of
the listIndicators() inline query that PostgREST projects as
/mart_indicator_summary on the public API.

Query shape: latest-year-per-indicator + group-by + value/null counts
filtered to active kommuner only. Inactive kommuner (historical
codes retained by upstream) are excluded from the counts so consumers
see "how many of today''s kommuner have data?" not "how many rows
exist?".

Refreshed nightly together with fact_kommune_indicators. The
upstream_updated column carries the most recent raw load timestamp
across the rows that contributed to this summary, so freshness can
be inspected per indicator without joining to raw.* sources.';
COMMENT ON COLUMN api_v1.indicator_summary.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''. Joins back to
fact_kommune_indicators.source_id and to the source declarations
in indicators/sources.yml.';
COMMENT ON COLUMN api_v1.indicator_summary.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde''). Combined with source_id forms the
natural key of this view.';
COMMENT ON COLUMN api_v1.indicator_summary.contents_label IS 'Human-readable label for contents_code, verbatim from upstream.
NULL only if every contributing row had a NULL label (rare).';
COMMENT ON COLUMN api_v1.indicator_summary.upstream_title IS 'What this series is ABOUT, from the source catalogue. The
subject was previously unreachable from this view — a
consumer used 8 of 195 series and missed the ones matching
its own question, because `contents_label` describes the
UNIT ("Andel (prosent)") and the subject lived only in an
opaque slug (urb-agents #1250, #1252). Joined from
mart_meta_sources; NULL only if a source is absent from the
catalogue, which `relationships` below asserts cannot happen.';
COMMENT ON COLUMN api_v1.indicator_summary.publisher IS 'Who publishes the upstream series (SSB, FHI, Bufdir, Brreg).
Joined from mart_meta_sources.';
COMMENT ON COLUMN api_v1.indicator_summary.eu_theme IS 'EU high-value-dataset theme. Populated for all 44 sources —
filter on it to ask "what does Atlas have about X?", which is
the question this view could not previously answer.';
COMMENT ON COLUMN api_v1.indicator_summary.tags IS 'Topic vocabulary from the source manifest, e.g.
[''provider:brreg'', ''topic:ngo-supply'']. Joined from
mart_meta_sources.

🔴 QUOTE THE VALUE. A tag contains a colon, and unquoted it is
rejected: `?tags=cs.{topic:ngo-supply}` returns 22P02 malformed
array literal. The working form is
`?tags=cs.{"topic:ngo-supply"}`.

⚠️ The unquoted spelling was published HERE, in this description,
until 2026-09-20 — so a consumer following the documentation got
an error and had to work the quoting out for itself (urb-agents
#1281). Same class as the `personer` description: the contract
said something a consumer acted on and it was wrong.';
COMMENT ON COLUMN api_v1.indicator_summary.latest_year IS 'Most recent calendar year for which this (source_id,
contents_code) has a VALUE in fact_kommune_indicators. The
coverage and value-range columns below are computed against
this year only.

🔴 THIS CHANGED ON 2026-09-21 AND THE OLD BEHAVIOUR WAS WRONG.
It was "has any rows", which pointed at years the publisher had
not released yet: upstream ships the full grid, so a row exists
with a NULL value. Seven of `ssb-06913`''s eight series resolved
to 2026 with `kommuner_with_value` 0 and both value bounds null
— a live series whose summary read as empty (urb-agents #1351).

⚠️ IT IS THE LATEST YEAR AN ACTIVE, NON-SENTINEL KOMMUNE HAS A
VALUE — the same subject the coverage below is counted over. A
first version filtered only on `value is not null` and was
defeated by SSB zero-filling retired kommune codes: 0101 Halden
(-2019) and 0801 Kragerø (-1959) carry a literal 0 for every
year forever, so the year looked populated while every active
kommune was null there. `latest_year` and `kommuners_with_value`
disagreed about which rows count (urb-agents #1354).

⚠️ A series with no value in ANY year keeps the newest year it
has rows for, rather than going null. Disappearing from the
catalogue is the worse failure: "0 of 357" invites a question,
an absent row does not.

⚠️ READ IT WITH `latest_year_window_years`. For a windowed
source this is the FIRST year of the window, not the year of
the data, and rendering it alone prints a date that is wrong by
up to four years.';
COMMENT ON COLUMN api_v1.indicator_summary.latest_year_window_years IS 'How many calendar years `latest_year` covers: 1 for an annual
series, 5 for `fhi-selvmord`, 3 for `fhi-mobbing`. The span is
`latest_year` to `latest_year + latest_year_window_years - 1`.

🔴 WHY IT IS A COLUMN AND NOT A SENTENCE. The window was already
stated in prose in this catalogue. On 2026-09-21 it was misread
twice in one day in opposite directions — a reviewer called a
live `fhi-selvmord` series six years stale, and a consumer
shipped the caption «Mobbetallene er fra 2022» for a 2022-2024
window. The consumer''s proposed workaround, matching `/1-year/i`
against the description, false-positives on `fhi-kpr-1aar`,
whose title contains "KPR 1-year" and which is annual anyway
(urb-agents #1331).

🔵 CROSS-CHECK IT AGAINST `meta_dimensions`, WHICH SAID ALL THIS
FIRST. `?code=in.(AAR,Tid)&select=source_id,meaning,value_format`
carries the upstream''s own description of its time dimension. On
2026-09-21 a consumer, ops-dev and this agent each derived the
windowing independently while that relation was already published
and already said it — and the claim "exactly two FHI sources are
windowed", used as evidence, was wrong; the catalogue named three
(urb-agents #1333).

⚠️ IT IS A `max()` OVER THE KOMMUNER AT `latest_year`, because
this view''s grain is one row per (source, contents_code) and the
window lives on the fact row. That is only honest if the window
is uniform across kommuner within an indicator-year, which is
asserted by the singular test
`window_is_uniform_within_an_indicator_year`. If that test ever
fails, this column is lossy and the failure is the warning.';
COMMENT ON COLUMN api_v1.indicator_summary.kommuner_with_value IS 'Count of active kommuner (kommune_is_active = true) that have a
non-NULL value for this indicator at latest_year. The headline
coverage number on the data explorer.';
COMMENT ON COLUMN api_v1.indicator_summary.kommuner_with_null IS 'Count of active kommuner that have a row at latest_year but
value IS NULL (i.e. upstream suppressed the cell). Inactive
kommuner are not counted.';
COMMENT ON COLUMN api_v1.indicator_summary.min_value IS 'Minimum non-NULL value across all rows at latest_year, regardless
of whether the kommune is active. NULL if no row had a value.';
COMMENT ON COLUMN api_v1.indicator_summary.max_value IS 'Maximum non-NULL value across all rows at latest_year, regardless
of whether the kommune is active. NULL if no row had a value.';
COMMENT ON COLUMN api_v1.indicator_summary.upstream_updated IS 'Most recent fact_kommune_indicators.updated_at across the rows
that contributed to this summary. Useful for staleness checks
per indicator without joining to raw.*.';

-- kommune_befolkning_alder  ←  marts.mart_kommune_befolkning_alder
CREATE OR REPLACE VIEW api_v1.kommune_befolkning_alder AS SELECT * FROM marts.mart_kommune_befolkning_alder;
COMMENT ON VIEW api_v1.kommune_befolkning_alder IS 'Population by kommune, year and age band — the denominator layer.
Published as api_v1.kommune_befolkning_alder.

Built from SSB table 07459 (age and sex distribution), which Atlas
has ingested and refreshed nightly for months while serving it to
nobody: nothing downstream of raw read it, so `GET /ssb-07459`
returned 404. A consumer built its elderly-care view around care
USERS rather than elderly RESIDENTS and wrote a README section
apologising for it, noting the substitution flatters a kommune with
a high threshold for granting services (urb-agents #1281).

⚠️ SIX BANDS SUM TO befolkning_total. TWO DO NOT — they are
roll-ups of the six, provided because PostgREST has aggregates
disabled and a consumer would otherwise add them client-side:

    sum to the total:  0_5 · 6_15 · 16_17 · 18_66 · 67_79 · 80_plus
    roll-ups:          0_17     = 0_5 + 6_15 + 16_17
                       67_plus  = 67_79 + 80_plus

Bands rather than a single "elderly" threshold on purpose. 67 is
defensible and it is still an editorial claim; publishing the bands
leaves that claim with whoever makes it, and the same rows serve as
the denominator for child poverty and working-age dependency.

⚠️ Counts are residents, not care recipients, and they are SSB''s
register population at the start of the year — not an average over
it. Historical kommune codes are excluded: only kommuner active
today get rows, so a 1990 row exists for today''s kommune, not for
the one that held that code in 1990.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.kommune_nr IS '4-digit kommune code. FK to dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.kommune_name IS 'Kommune name in bokmål, joined from dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.fylke_nr IS '2-digit fylke code, derived from kommune_nr in dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.fylke_name IS 'Joined from dim_fylke. NULL for kommune codes whose fylke has no row there — Svalbard-style 21xx codes. A LEFT join on purpose: an inner one would drop those kommuner from the denominator entirely, which is worse than a missing label.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.year IS 'Calendar year. SSB 07459 covers 1986 onwards.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_0_5 IS 'Residents aged 0-5 (pre-school). Disjoint band.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_6_15 IS 'Residents aged 6-15 (grunnskole age). Disjoint band.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_16_17 IS 'Residents aged 16-17. Disjoint band, and the one that completes 0_17.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_18_66 IS 'Residents aged 18-66 (working age, to the 67 pension threshold). Disjoint band.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_67_79 IS 'Residents aged 67-79. Disjoint band.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_80_plus IS 'Residents aged 80 and over, including SSB''s open-ended ''105+'' bucket. Disjoint band. Built from age_min, not age_int — age_int is NULL for ''105+'', so banding on it would silently drop those residents.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_0_17 IS 'Residents aged 0-17. ⚠️ A ROLL-UP of 0_5 + 6_15 + 16_17, NOT a
seventh band — adding it to the disjoint bands double-counts.
The child-poverty denominator, so that coverage_gap_barnefattigdom''s
share can be read against a population rather than against itself.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.alder_67_plus IS 'Residents aged 67 and over. ⚠️ A ROLL-UP of 67_79 + 80_plus, NOT a
band. This is the elderly denominator the consumer in #1281 did not
have; 67 is Norway''s pension age and the choice of threshold is the
reader''s, which is why the two bands are published beside it.';
COMMENT ON COLUMN api_v1.kommune_befolkning_alder.befolkning_total IS 'All residents of the kommune in that year. Equals the six disjoint
bands summed.

🔴 Sexes are FILTERED, not summed: SSB''s Kjonn dimension codes ''0'' as
ALL, so summing every sex row would double the population of every
kommune in Norway. The model selects male and female explicitly, and
the singular test bands_sum_to_the_population_total is what would
catch it if that ever stopped being true.';

-- kommune_local_chapters  ←  marts.mart_kommune_local_chapters
CREATE OR REPLACE VIEW api_v1.kommune_local_chapters AS SELECT * FROM marts.mart_kommune_local_chapters;
COMMENT ON VIEW api_v1.kommune_local_chapters IS '🔵 EXPECTED EMPTY TODAY, AND THAT IS NOT A DEFECT. Its one row per local chapter, so it is empty until Red Cross chapter data is loaded.
Terje''s position, 2026-09-21: the Red Cross data is not coming now, it
will be there later. The relation is published and answers so a consumer
can build against its shape before the rows arrive.

⚠️ A consumer cannot tell "empty by design" from "broken" without being
told, and two of these three were asked about on the day someone noticed
(urb-agents #1351). If this relation is still empty and this note is
gone, something regressed.

Active local chapters in each kommune, decorated with the NGO
name/brand and the service-category labels offered. Backs the
kommune detail page (atlas-frontend /kommuner/[kommune_nr]);
equivalent to listChaptersInKommune().

**Important:** this view returns *multiple rows per chapter* —
one per service category the chapter offers. A chapter that
provides three service categories appears as three rows for the
same kommune_nr / chapter_id, with different
service_category_code values. Consumers that want unique chapters
should distinct on chapter_id (or aggregate service categories
into an array client-side).

GRAIN: one row per (kommune_nr, chapter_id,
service_category_code), asserted by a test rather than only
described here. It is neither one row per chapter nor one row per
chapter-kommune coverage relation — a consumer told us those were
the two shapes it would guess between (urb-agents #1289).

PostgREST consumers filter via ?kommune_nr=eq.X. Inactive
chapters, non-local chapters (regional, national), and chapters
with NULL kommune_nr are excluded. ⚠️ Excluding regional chapters
means the kommuner a regional chapter serves do NOT appear here;
see kommune_nr for why that gap is not closed elsewhere either.
Svalbard (Longyearbyen Røde Kors) is included even though no 21xx
code is in dim_kommune — the FK relationships test is
`warn`-severity to keep this row visible.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.kommune_nr IS '🔴 WHERE THE CHAPTER IS REGISTERED, NOT WHERE IT WORKS. This
description said "where the local chapter operates" until
2026-09-20 and that was a stronger claim than the data
supports: the value is a dim_postnummer lookup on the
chapter''s POSTAL ADDRESS (see supply__redcross_branches).

⚠️ So a chapter serving three neighbouring kommuner appears in
one of them, and a chapter with a PO box in the next kommune
appears in the wrong one. A consumer asking "is Røde Kors
here?" gets "is Røde Kors registered here?" — which is the
same limitation as searching the Enhetsregisteret by name, and
this relation does not remove it (urb-agents #1289).

Declared service areas are not modelled for Red Cross at all.
`marts.chapter_kommune_coverage` holds one row per
(regional chapter, kommune), but its rows are INFERRED from
where the regional chapter''s local children are registered —
so it inherits this same defect rather than fixing it, and it
is not published to api_v1.

FK to dim_kommune, the primary filter dimension for this view.
Chapters with NULL kommune_nr are excluded (this isn''t "local
chapters in a kommune" if there''s no kommune).

⚠️ The relationships test is `warn`-severity because
Longyearbyen Røde Kors is a real chapter whose Svalbard code
is not in dim_kommune — SSB Klass 131 contains no 21xx code.
So this relation is built to publish a Svalbard row that no
dimension can describe. See urb-agents #700.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.chapter_id IS 'Composite slug for the local chapter (e.g.
''redcross-oslo-grunerløkka''). Repeats across rows when the
chapter offers multiple service categories.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.name IS 'Display name for the local chapter.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO that owns the chapter.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_name IS 'Joined from dim_ngo (legal name).';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_brand_name IS 'Joined from dim_ngo (brand name when distinct from legal
name). NULL when the NGO doesn''t use a brand alias.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.service_category_code IS 'ICNPO-derived service category code for one of the activities
this chapter offers. Combined with chapter_id forms the
natural key of this view (rows are unique on
(chapter_id, service_category_code)).';
COMMENT ON COLUMN api_v1.kommune_local_chapters.service_category_label_no IS 'Human-readable Norwegian label for service_category_code,
joined from ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.sort_order IS 'Display order from ref_atlas_service_category. Used by the UI
to render service categories in a consistent sequence; carry
on the row so consumers can sort without a separate query.';

-- kommune_ngo_summary  ←  marts.mart_kommune_ngo_summary
CREATE OR REPLACE VIEW api_v1.kommune_ngo_summary AS SELECT * FROM marts.mart_kommune_ngo_summary;
COMMENT ON VIEW api_v1.kommune_ngo_summary IS 'Active voluntary organisations per kommune and ICNPO category —
the number a consumer previously had to download the whole
register to compute. Published as api_v1.kommune_ngo_summary.

PostgREST has aggregates disabled, so `?select=count()` returns
400 and the only alternatives were ~15 minutes of per-kommune
probes or a 2.8 MB CSV on every page load. One consumer shipped
the download (urb-agents #1250, finding 1); this replaces it with
~12 000 rows.

⚠️ Counts here will NOT match a count over brreg_enhet. 7 488 of
72 792 active voluntary units (10.3 %) carry no kommune_nr — that
is what Brreg publishes — and cannot be attributed to a
municipality. A handful more sit on codes outside the 357 active
kommuner and are dropped by the join.

A (kommune, category) pair absent from this view has zero
organisations; rows are not emitted for empty combinations.

⚠️ CHANGED 2026-09-21: SSB''s 9999 ''Uoppgitt'' is no longer
included. It is a current code, so `is_active` never excluded it,
and this relation had been reporting a place that does not exist.
Counts drop by that row. `dim_kommune` still carries 9999 — the
dimension mirrors SSB''s list — and the value is published in
`unattributed_totals` (urb-agents #1301).

⚠️ COST, AND ONE LOAD-BEARING DEPENDENCY. Measured end-to-end
against the live API: 0.12 s filtered by kommune_nr, 0.205-0.326 s
unfiltered for all rows. Before the covering index on
dim_brreg_enhet it was 25 s cold for a 24 kB response and one
request timed out. That index is not an optimisation — drop it and
this relation is unusable rather than slow.';
COMMENT ON COLUMN api_v1.kommune_ngo_summary.kommune_nr IS '4-digit kommune code. FK to dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_ngo_summary.kommune_name IS 'Kommune name in bokmål, joined from dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_ngo_summary.icnpo_nummer IS 'ICNPO category number as Brreg assigns it. NULL where the
organisation carries no ICNPO classification.';
COMMENT ON COLUMN api_v1.kommune_ngo_summary.icnpo_kategori IS 'ICNPO category label. NULL where the organisation carries no
ICNPO classification — those rows are counted, not dropped,
so a per-kommune total over this view stays correct.';
COMMENT ON COLUMN api_v1.kommune_ngo_summary.active_count IS 'Count of organisations in this kommune and category that are
both is_active and registrert_i_frivillighetsregisteret.
Always >= 1; absent combinations mean zero.';

-- kommune_ngo_totals  ←  marts.mart_kommune_ngo_totals
CREATE OR REPLACE VIEW api_v1.kommune_ngo_totals AS SELECT * FROM marts.mart_kommune_ngo_totals;
COMMENT ON VIEW api_v1.kommune_ngo_totals IS 'One row per kommune: how many active voluntary organisations are
registered there. 357 rows instead of the ~5 400 in
kommune_ngo_summary. Published as api_v1.kommune_ngo_totals.

Exists because PostgREST cannot sum — `?select=active_count.sum()`
returns PGRST123, aggregates are disabled — so a consumer wanting
one number per kommune otherwise fetches every category row and
adds them client-side. That was most of a cold page load
(urb-agents #1265).

⚠️ Counts exclude the 10.3 % of active voluntary units carrying no
kommune_nr, exactly as kommune_ngo_summary does. Summing this gives
the placed total, not the register total.

⚠️ CHANGED 2026-09-21: SSB''s 9999 ''Uoppgitt'' is no longer
included. It is a current code, so `is_active` never excluded it,
and this relation had been reporting a place that does not exist.
Counts drop by that row. `dim_kommune` still carries 9999 — the
dimension mirrors SSB''s list — and the value is published in
`unattributed_totals` (urb-agents #1301).

⚠️ COST, AND ONE LOAD-BEARING DEPENDENCY. Measured end-to-end
against the live API: 0.12 s filtered by kommune_nr, 0.205-0.326 s
unfiltered for all rows. Before the covering index on
dim_brreg_enhet it was 25 s cold for a 24 kB response and one
request timed out. That index is not an optimisation — drop it and
this relation is unusable rather than slow.';
COMMENT ON COLUMN api_v1.kommune_ngo_totals.kommune_nr IS '4-digit kommune code. FK to dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_ngo_totals.kommune_name IS 'Kommune name in bokmål, joined from dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_ngo_totals.active_count IS 'Total active voluntary organisations in this kommune, summed
across ICNPO categories. Always >= 1; a kommune with none has
no row.';

-- meta_dimensions  ←  marts.mart_meta_dimensions
CREATE OR REPLACE VIEW api_v1.meta_dimensions AS SELECT * FROM marts.mart_meta_dimensions;
COMMENT ON VIEW api_v1.meta_dimensions IS 'Per-source × per-dimension catalogue. Backs the "what does this
column mean" panel on `/data/sources/[source_id]` (customer
frontend, PLAN-007 phase 4) and exposes editorial semantics
shoppers would otherwise have to leave Atlas to find on the
upstream''s docs site.

v1 scope (this PR): editorial pass-through over the
`_sources_dimensions` seed (4 columns: `meaning`, `value_format`,
`notes`). The `cardinality`, `example_values`, and `null_count`
columns from PLAN-007 phase 3.4''s full spec require introspecting
`raw.<source>` tables with per-source column-name rules — deferred
to a follow-up PR. See `mart_meta_dimensions.sql` header for the
open question (Jinja loop vs separate Python extract script vs
per-source `column_name:` field in manifest.yml).

Row count = same as `_sources_dimensions` (~216, growing with
every new source × upstream-dimension).';
COMMENT ON COLUMN api_v1.meta_dimensions.source_id IS 'Source the dimension belongs to. Joins to
`mart_meta_sources.source_id` and `_sources_manifest.source_id`.';
COMMENT ON COLUMN api_v1.meta_dimensions.code IS 'Upstream''s own dimension code (e.g. `Region`, `Tid`,
`ContentsCode` for SSB; `GEO`, `AAR`, `KJONN`, `MEASURE_TYPE`
for FHI). Verbatim from the source''s API/export — not
translated to canonical Atlas vocabulary.';
COMMENT ON COLUMN api_v1.meta_dimensions.meaning IS 'Short human-readable description of what the dimension
represents. Hand-authored editorial content from each source''s
`manifest.yml` `dimensions:` block.';
COMMENT ON COLUMN api_v1.meta_dimensions.value_format IS 'Encoding of values within the dimension (e.g. "4-digit year as
text", "1- to 6-character numeric code"). Empty string when no
specific format applies.';
COMMENT ON COLUMN api_v1.meta_dimensions.notes IS 'Editorial notes — code-list size, semantic gotchas, downstream
filtering decisions. Empty string when no notes apply.';

-- meta_endpoints  ←  marts.mart_meta_endpoints
CREATE OR REPLACE VIEW api_v1.meta_endpoints AS SELECT * FROM marts.mart_meta_endpoints;
COMMENT ON VIEW api_v1.meta_endpoints IS 'One row per queryable Atlas endpoint, with tags inherited from
upstream sources via the lineage graph and a `layer:<schema>` tag
from the schema. Wraps to `api_v1.meta_endpoints` and backs the
tag-filter catalogue at `/data` in the customer frontend
(PLAN-007 phase 4).

🔵 THIS IS THE INDEX, SO IT SAYS WHERE THE OTHER TWO CATALOGUES
ARE: `meta_sources` for one row per ingest source (licence,
publisher, freshness), and `meta_dimensions` for one row per
source × upstream dimension — what each coded column means and
its value format. A consumer enumerating relations here should
not have to read 19 descriptions to discover the second one
(urb-agents #1335).

Includes endpoints from `api_v1.*`, `marts.*`, and `raw.*`
(Atlas''s three open-by-default schemas; `private_marts.*` stays
auth-gated and is excluded). Skips internal seeds prefixed `_`
(`_sources_manifest`, `_sources_dimensions`) and any `dbt_*`
diagnostic tables.

Tag inheritance uses the **union** rule: a `mart_*` derived from
many sources picks up every source''s `provider:`, `topic:`,
`geo:`, `cadence:`, and `eu_theme:` tag, deduped. Filter
"involves something annual" beats "purely annual" — see PLAN-007
phase 3.2 for the design rationale.';
COMMENT ON COLUMN api_v1.meta_endpoints.endpoint IS 'Schema-qualified table/view identifier (`<schema>.<table>`).
Primary key.';
COMMENT ON COLUMN api_v1.meta_endpoints.schema_name IS 'One of `api_v1`, `marts`, `raw`.';
COMMENT ON COLUMN api_v1.meta_endpoints.table_name IS 'Bare table/view name without schema qualification.';
COMMENT ON COLUMN api_v1.meta_endpoints.tags IS '`text[]` carrying the layer tag (`layer:<schema>`) plus inherited
source tags via union semantics. Filter via PostgREST''s
`?tags=cs.{...}` array-contains operator.';
COMMENT ON COLUMN api_v1.meta_endpoints.is_public_api IS '`true` when `schema_name = ''api_v1''`. Lets clients distinguish
stable-contract endpoints from the broader `marts.*` / `raw.*`
surfaces that are queryable but not version-guaranteed.';
COMMENT ON COLUMN api_v1.meta_endpoints.table_type IS '`BASE TABLE` for tables (most `marts.*`, all `raw.*`) and
`VIEW` for views (all `api_v1.*` wrappers).

⚠️ IN `api_v1` IT IS ALWAYS `VIEW` AND THEREFORE TELLS YOU
NOTHING ON ITS OWN. All 17 public relations are views over a
`marts.mart_*` relation; this column distinguishes them from
`marts.*` and `raw.*`, not from each other.

🔴 IT DOES NOT PREDICT WHETHER `Prefer: count=estimated` CAN BE
TRUSTED. Three cases, and the deciding property is whether the
aggregation happened BEFORE the planner saw it:

1. the mart is a TABLE — 14 of 17. Its rows were counted by
   ANALYZE when it was built, whatever its query did, so the
   estimate is accurate. `indicator_summary` aggregates heavily
   and estimates fine, because the aggregating happened at
   build time.
2. the mart is a PLAIN VIEW — `brreg_enhet`. Row count
   propagates from the base table. Accurate.
3. the mart is an AGGREGATING VIEW — `kommune_ngo_summary` and
   `kommune_ngo_totals`, and only these. The planner must guess
   how many groups a GROUP BY will produce, and measured on the
   live API 2026-09-20 it guessed badly:

       kommune_ngo_summary   exact 5 435   estimated 69 462   12.8x
       kommune_ngo_totals    exact   357   estimated  6 946   19.5x

⚠️ AND SEPARATELY, `estimated = 1` DOES NOT MEAN ONE ROW. It is
the planner''s floor, so an EMPTY relation reports 1 — measured
on activity_catalog, distrikt_summary and kommune_local_chapters,
all of which hold zero rows and all of which are case 1. A
consumer asking "is there any data here?" cheaply gets yes.

✅ Use `Prefer: count=exact`. The largest published relation is
~72 000 rows and an exact count is cheap; the estimate saves
nothing worth being wrong about.

🔵 An earlier version of this description said the split was
tables versus views. There are no tables in api_v1, so that
rule was unusable — a consumer checking dim_kommune, a view
that estimates exactly, would have concluded the documentation
was wrong (urb-agents #1288).';

-- meta_sources  ←  marts.mart_meta_sources
CREATE OR REPLACE VIEW api_v1.meta_sources AS SELECT * FROM marts.mart_meta_sources;
COMMENT ON VIEW api_v1.meta_sources IS 'Per-source catalogue row — one per ingest source in
`_sources_manifest`, joined to `raw.ingest_runs` aggregates so
consumers see freshness alongside the static metadata. Wraps to
`api_v1.meta_sources` and backs `/data/sources` in the customer
frontend (PLAN-007 phase 4).

🔴 THIS RELATION DESCRIBES A SOURCE, NOT ITS COLUMNS. For what an
upstream dimension MEANS — what `AAR` is, whether a code is a
kommune, whether a year is a single year or a window — read
`meta_dimensions`, one row per source × dimension with the
upstream''s own words and the value format.

⚠️ THIS POINTER EXISTS BECAUSE ITS ABSENCE COST A DAY. On
2026-09-21 a consumer read all 21 descriptions here, concluded
"exactly two sources use multi-year windows", and shipped a wrong
year on a front page. `meta_dimensions` said `"3-year rolling
cohort"` for a third the whole time. Reading every row of this
relation is thorough and structurally incapable of answering a
question about a dimension (urb-agents #1335).

Tags column is a Postgres `text[]` carrying the four declared
namespaces (`provider:`, `topic:`, `geo:`, `cadence:`) plus the
`eu_theme:` namespace. The customer frontend renders each as a
filter pill; PostgREST consumers filter via `?tags=cs.{"provider:ssb"}`
— the quotes are required, because the value contains a colon.

`last_ingested_at` and `last_upstream_update_at` come from
`raw.ingest_runs` aggregated over successful (`exit_code = 0`)
runs. Sources whose ingest module hasn''t yet captured the
upstream''s "updated" field leave `last_upstream_update_at` NULL —
that''s the design (`raw.ingest_runs.upstream_updated_at` is
nullable per migration 028).

`downstream_model_count` is the number of distinct dbt models
that derive from this source via the `lineage` seed (Phase 3.3).
0 for sources whose data hasn''t yet been wired into a mart.';
COMMENT ON COLUMN api_v1.meta_sources.source_id IS 'Atlas catalogue id; primary key. Matches `_sources_manifest.source_id`.';
COMMENT ON COLUMN api_v1.meta_sources.upstream_id IS 'Upstream''s own identifier (SSB table number, FHI dataset slug, etc.).';
COMMENT ON COLUMN api_v1.meta_sources.upstream_url IS 'Canonical link to the data on the upstream''s site (often the API endpoint).';
COMMENT ON COLUMN api_v1.meta_sources.upstream_landing_page IS 'Human-browsable web page describing the dataset (DCAT-AP `dcat:landingPage`).
Empty when `upstream_url` is already browsable; clients fall back to that.';
COMMENT ON COLUMN api_v1.meta_sources.upstream_title IS 'Source''s authoritative title at the upstream (usually Norwegian).';
COMMENT ON COLUMN api_v1.meta_sources.description IS 'One-paragraph framing for the customer-facing catalogue.';
COMMENT ON COLUMN api_v1.meta_sources.publisher IS 'Institution that publishes the data.';
COMMENT ON COLUMN api_v1.meta_sources.license IS 'License token (e.g. `NLOD`); see `license_url` for terms.';
COMMENT ON COLUMN api_v1.meta_sources.license_url IS 'URL of the license terms.';
COMMENT ON COLUMN api_v1.meta_sources.periodicity IS 'Update cadence as ISO 8601 (`P1Y` / `P3M` / `P1M` / `P1D`)
or `irregular`. More precise than the `cadence:` tag.';
COMMENT ON COLUMN api_v1.meta_sources.eu_theme IS 'EU Publications Office Data Theme code (one of 13: `AGRI`, `ECON`,
`EDUC`, `ENER`, `ENVI`, `GOVE`, `HEAL`, `INTR`, `JUST`, `REGI`,
`SOCI`, `TECH`, `TRAN`). Aligns with Felles datakatalog / DCAT-AP.';
COMMENT ON COLUMN api_v1.meta_sources.attribution IS 'Citation string for academic / legal compliance (e.g.
"Kilde: Statistisk sentralbyrå, tabell 08764").';
COMMENT ON COLUMN api_v1.meta_sources.tags IS '`text[]` of namespaced tags: `provider:<X>`, `topic:<X>`,
`geo:<X>`, `cadence:<X>`, `eu_theme:<X>`. Filter via PostgREST''s
array-contains operator, QUOTING the value because it contains a
colon: `?tags=cs.{"topic:ngo-supply"}`. Unquoted it returns 22P02
malformed array literal. Always 5 entries (one per declared
namespace).';
COMMENT ON COLUMN api_v1.meta_sources.last_ingested_at IS '`MAX(finished_at)` from `raw.ingest_runs` filtered to
successful runs (`exit_code = 0`). NULL until the source has
at least one successful run on the current cluster.';
COMMENT ON COLUMN api_v1.meta_sources.last_upstream_update_at IS '`MAX(upstream_updated_at)` from successful ingest runs.
NULL when the source hasn''t run yet OR its ingest module
doesn''t capture the upstream''s "updated" field (Red Cross
web scrape, Brreg per-entity fetch).';
COMMENT ON COLUMN api_v1.meta_sources.latest_row_count IS '`rows_parsed` from the most recent successful run. NULL when
the source has zero successful runs on the current cluster.';
COMMENT ON COLUMN api_v1.meta_sources.total_runs IS 'Count of successful runs ever recorded for this source. 0 when
no successful run exists.';
COMMENT ON COLUMN api_v1.meta_sources.downstream_model_count IS 'Number of distinct downstream dbt models that derive from this
source via the `lineage` seed. 0 for sources not yet wired
into a mart.

🔴 DO NOT READ THIS AS "IS IT SERVED". It counts models, and a
model is not a consumer surface. A source feeding 357 rows into
a published relation and a source whose only model reaches
nothing both report a positive count. Use `served_as`.

⚠️ On 2026-09-21 this field produced a statement to a consumer
that "the eight FHI sources" were served, when it was seven —
`fhi-innvandrere` has one model, 32,720 rows and no published
series. Four parties had each built a different partial proxy
for the question this field looks like it answers, and three
were wrong the same day (urb-agents #1344).

🔴 AND THIS NUMBER CAN CHANGE FOR TWO REASONS THAT LOOK
IDENTICAL. Either a model genuinely shipped, or the lineage it
is computed from was CORRECTED. A consumer reading it twice
cannot tell an honest value change from an accuracy fix: on
2026-09-21 the demo consumer read it morning and evening, got
9 and 1, and had no way to know which it was seeing
(urb-agents #1348).

🔵 `lineage` is generated from the dbt manifest and committed,
so it can be stale — 103 edges were missing that day, some for
weeks. `check-lineage-is-current.sh` now fails CI on drift, so
the accuracy kind of change should stop happening. It cannot
be detected retroactively in a value you already read.';
COMMENT ON COLUMN api_v1.meta_sources.served_as IS 'The `api_v1` relations a consumer can actually reach this source
through, as a Postgres `text[]`. **Empty means nothing published
depends on it** — that is the gap, and it is the one question
`downstream_model_count` cannot answer.

Filter for the gap with `?served_as=eq.{}`, or for a specific
surface with `?served_as=cs.{indicator_summary}`.

🔵 NOT A PLAIN LINEAGE JOIN, DELIBERATELY. A relation derived
from `fact_kommune_indicators` is only claimed when the source
actually has rows in that fact.

The case that forced that design: `ssb-06913` fed the fact and
so reached four published relations on paper while contributing
ZERO rows to them — its `kommune_nr` regex never matched, so
783,104 rows were discarded downstream. A structural boolean
would have called it served and become the fifth wrong proxy.
It was fixed the same day (urb-agents #1345) and now reports
those four relations, which is the column working rather than
the example expiring.

⚠️ THE CATALOGUE RELATIONS ARE EXCLUDED. `meta_sources`,
`meta_endpoints` and `meta_dimensions` hold a row for every
source by construction, so naming them would be the same value
on every row. They describe a source; they do not serve it.

🔴 IT DOES NOT ASSERT THAT ANY NAMED RELATION CONTAINS ROWS.
For a relation derived from the fact, the source is checked to
have rows there. For every other relation the claim is
LINEAGE ONLY — what the source WOULD serve if it had data.

⚠️ THE CASE THAT PROVES IT: `redcross-branches` has
`total_runs` 0 and has never ingested, and it still lists five
relations, three of which hold zero rows. A source that has
never run looks served.

🔵 THE COMPANION CHECK IS ON THIS SAME ROW. Read `served_as`
with `total_runs` and `latest_row_count`: lineage says what
could arrive, those say whether anything did.

⚠️ AN EARLIER VERSION OF THIS PARAGRAPH SAID THE SAME THING AND
DID NOT WORK. It read "for non-fact relations this is
reachability, not volume", naming `brreg_enhet` and
`dim_kommune` — relations that are never empty, so the warning
was abstract. ops-dev read it and built a gate on the field
within the hour (urb-agents #1346). A caveat that names no
failing case is a caveat nobody applies.

🔵 Excluding never-ingested sources outright was considered and
rejected: it would collapse "has never run" into "is not
modelled", losing the distinction between `redcross-branches`
(five relations waiting for data) and the sources deferred in
BACKLOG (no relation at all). Say the word if that trade is
wrong.

🔵 Derived from the same artefact the CI gate reads, so the two
cannot drift: `check-every-source-is-served.sh` and this column
both resolve the source against the generated `api_v1` relation
list.

⚠️ THE GATE AND THIS COLUMN CAN DISAGREE, AND THAT IS CORRECT.
The gate is static and cannot see a source that is wired up and
delivers nothing, so it will report fewer gaps than this column
does. The gate answers "is it wired"; this answers "does it
arrive". Neither count is written here on purpose — a number in
a published description goes stale silently, which is most of
why this column had to be written at all.';

-- ngo_index  ←  marts.mart_ngo_index
CREATE OR REPLACE VIEW api_v1.ngo_index AS SELECT * FROM marts.mart_ngo_index;
COMMENT ON VIEW api_v1.ngo_index IS 'One row per NGO in dim_ngo with chapter_count and has_supply
decorations. Backs the NGO landing page (atlas-frontend /ngo) and
is equivalent to the listNgos() inline query.

chapter_count counts only active chapters (dim_chapter.is_active),
so a defunct NGO sits at 0 even if its historical chapters are
retained. has_supply is the convenience boolean (chapter_count > 0).
The full table is small (~11 rows in v1, growing as new NGOs
land), so PostgREST consumers typically read all of it.';
COMMENT ON COLUMN api_v1.ngo_index.orgnr IS '9-digit Brreg organisasjonsnummer (text — leading zeros are
preserved). Natural key for this view.';
COMMENT ON COLUMN api_v1.ngo_index.slug IS 'kebab-case URL-friendly identifier (e.g. ''redcross'', ''kirkens-bymisjon'').';
COMMENT ON COLUMN api_v1.ngo_index.name IS 'Legal name from Brreg.';
COMMENT ON COLUMN api_v1.ngo_index.brand_name IS 'Common brand name when distinct from legal name (e.g.
''Sanitetskvinnene'' vs N.K.S.). NULL when the brand equals
the legal name.';
COMMENT ON COLUMN api_v1.ngo_index.website_url IS 'NGO''s primary website. Used as the outbound link from the index page.';
COMMENT ON COLUMN api_v1.ngo_index.tier IS 'Structural-fit tier (A / B / C) from
docs/research/ngo-landscape.md. v1 includes Tier A only.';
COMMENT ON COLUMN api_v1.ngo_index.chapter_data_shape IS 'How this NGO''s per-chapter activity data is shaped — drives
which ingest pattern it uses. Values: ''api_canonical'',
''cms_bins'', ''programme_only'', ''no_structure''.';
COMMENT ON COLUMN api_v1.ngo_index.has_chapters IS 'Whether this NGO DECLARES that it has chapters — an editorial fact
from dim_ngo, recorded when the organisation is curated.

Not the same question as has_supply, which is chapter_count > 0 and
therefore an ingest OUTCOME: does Atlas hold chapter rows for this
organisation yet. They agree today only because all curated NGOs
declare has_chapters true and all have been ingested. The first NGO
curated before its chapters land makes them disagree, and a consumer
filtering on the wrong one loses it without an error.';
COMMENT ON COLUMN api_v1.ngo_index.primary_focus IS 'One-line description of the NGO''s main mission area.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_1 IS 'ICNPO classification code (primary). See ref_icnpo. NULL when
unclassified.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_2 IS 'ICNPO classification code (secondary). NULL when not used.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_3 IS 'ICNPO classification code (tertiary). NULL when not used.';
COMMENT ON COLUMN api_v1.ngo_index.chapter_count IS 'Count of active chapters for this NGO (filtered by
dim_chapter.is_active = true). Zero if the NGO has no chapters
or all chapters are dormant.';
COMMENT ON COLUMN api_v1.ngo_index.has_supply IS 'Convenience boolean: chapter_count > 0. True when the NGO has
at least one active chapter — i.e. it appears on the supply
side of Atlas.';

-- ngo_overview  ←  marts.mart_ngo_overview
CREATE OR REPLACE VIEW api_v1.ngo_overview AS SELECT * FROM marts.mart_ngo_overview;
COMMENT ON VIEW api_v1.ngo_overview IS 'One row per NGO in dim_ngo with the six count metrics shown on
the per-NGO landing page (atlas-frontend /ngo/[slug]).
Equivalent to the getNgoOverview() inline query, but precomputed
for all NGOs so PostgREST projects it as a single endpoint
consumers filter via ?orgnr=eq.X.

Counts include both active and inactive chapters in the
level-specific buckets (national/regional/local). kommune_count
counts distinct kommune_nr only across *active* local chapters,
matching the original query''s behaviour.';
COMMENT ON COLUMN api_v1.ngo_overview.orgnr IS '9-digit Brreg organisasjonsnummer. Natural key for this view.';
COMMENT ON COLUMN api_v1.ngo_overview.chapter_count IS 'Total count of chapters for this NGO across all levels (active + inactive).';
COMMENT ON COLUMN api_v1.ngo_overview.national_count IS 'Count of chapters at chapter_level = ''national''.';
COMMENT ON COLUMN api_v1.ngo_overview.regional_count IS 'Count of chapters at chapter_level = ''regional'' (e.g. Red Cross distrikt).';
COMMENT ON COLUMN api_v1.ngo_overview.local_count IS 'Count of chapters at chapter_level = ''local'' (the kommune-bound branches).';
COMMENT ON COLUMN api_v1.ngo_overview.activity_count IS 'Count of distinct activities offered by this NGO (rows in
dim_activity for this orgnr).';
COMMENT ON COLUMN api_v1.ngo_overview.kommune_count IS 'Count of distinct kommuner with at least one active local
chapter for this NGO. The "footprint" metric for coverage-gap
questions.';

-- unattributed_totals  ←  marts.mart_unattributed_totals
CREATE OR REPLACE VIEW api_v1.unattributed_totals AS SELECT * FROM marts.mart_unattributed_totals;
COMMENT ON VIEW api_v1.unattributed_totals IS 'The part of a published quantity that belongs to no municipality.
Published as api_v1.unattributed_totals.

🔴 Atlas had no convention for this, and the two surfaces that met
it chose opposite wrong answers: SSB''s 9999 ''Uoppgitt'' sits INSIDE
a per-kommune relation and corrupts any sum over it, while 7 488
active voluntary units with no kommune_nr fall OUT of one and
vanish silently. One smuggles the remainder in as a row, the other
discards it, and a consumer summing either gets a number that is
wrong in a direction it cannot see (urb-agents #700, #1250, #1265).

✅ The rule this establishes: the VALUE belongs, the ROW does not.
A per-kommune relation carries only kommuner; the remainder lives
here, named, so reconciling to a national total is a deliberate
act rather than an accident of whether a sentinel survived a
filter.

⚠️ It does NOT remove the 9999 rows from dim_kommune or
coverage_gap_barnefattigdom. That is a breaking contract change —
`?is_active=eq.true` would return 357 instead of 358 with no
warning — and it is deliberately not bundled with an additive
change. `is_sentinel` remains a stopgap and this view does not
make the trap gone.

🔵 A zero is a result. Where the remainder is genuinely nothing
this emits 0 rather than omitting the row: "we checked, none" and
"nobody checked" are different answers, and a missing row cannot
tell them apart.

✅ THE ARITHMETIC CLOSES, AND A TEST SAYS SO. Summing a per-kommune
relation and adding every `unattributed_value` for it must equal
`total_value`:

    kommune_ngo_totals   65 270
    no_kommune_nr         7 489
    kommune_nr_not_current   43
    ---------------------------
    total_value          72 802

⚠️ It did not close on the day this shipped. It named 7 489 of
7 532 and the 43 Svalbard organisations were counted by neither
relation — silent, self-consistent, and visible only by doing the
subtraction this view exists to support. The singular test
`the_remainder_closes_the_total` now asserts the decomposition
rather than the parts, which is the thing that was missing: every
part had a test and the relationship between them had none.';
COMMENT ON COLUMN api_v1.unattributed_totals.relation IS 'The published relation this remainder belongs to, e.g. `kommune_ngo_totals`. Not a foreign key: it names a relation, not a row.';
COMMENT ON COLUMN api_v1.unattributed_totals.measure IS 'The column of that relation the value would have contributed to.';
COMMENT ON COLUMN api_v1.unattributed_totals.reason IS 'Why the value is unattributable.

`no_kommune_nr` — upstream publishes the record with no
municipality at all. For Brreg this is 10.3 % of active
voluntary units and is what Brreg itself publishes; it is not
an Atlas defect.

`kommune_nr_not_current` — the record HAS a kommune_nr and it
is not one of the current municipalities. 🔴 Today these are
all Svalbard (2100): a real code, absent from SSB''s Klass 131,
so `kommune_ngo_totals` emits no row for it. Without this
reason the relation named 7 489 of 7 532 and the obvious
reconciliation came out 43 short with no error anywhere
(urb-agents #1318). Historical kommune codes would land here
too if Brreg ever used one.

`sentinel_9999` — upstream attributes the value to its own
''Uoppgitt'' bucket. ⚠️ Note this is the same 9999 that
`classify_region_code` calls `unspecified_national` and that
`dim_kommune.is_active` still returns as a municipality.';
COMMENT ON COLUMN api_v1.unattributed_totals.source_id IS 'The upstream source the quantity comes from.';
COMMENT ON COLUMN api_v1.unattributed_totals.year IS 'Calendar year, where the quantity is time-varying. NULL for register snapshots like Brreg, which have no year dimension — a null here means "not applicable", never "unknown".';
COMMENT ON COLUMN api_v1.unattributed_totals.unattributed_value IS 'The part that belongs to no municipality. Add this to a sum over the per-kommune relation to reconcile with the upstream national figure.';
COMMENT ON COLUMN api_v1.unattributed_totals.total_value IS 'The whole quantity, attributed and unattributed together. The denominator for the share.';
COMMENT ON COLUMN api_v1.unattributed_totals.unattributed_share_pct IS '`unattributed_value` as a percentage of `total_value`, to one decimal. NULL when total_value is zero, because a share of nothing is undefined rather than zero.';

-- Grant SELECT to the per-app anon role if it exists (created by UIS's
-- ./uis configure postgrest --app atlas). Guarded so this migration
-- applies cleanly against environments where UIS hasn't run configure yet.
DO $$ BEGIN
  IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'atlas_web_anon') THEN
    GRANT USAGE ON SCHEMA api_v1 TO atlas_web_anon;
    GRANT SELECT ON ALL TABLES IN SCHEMA api_v1 TO atlas_web_anon;
    ALTER DEFAULT PRIVILEGES IN SCHEMA api_v1
      GRANT SELECT ON TABLES TO atlas_web_anon;
  END IF;
END $$;

-- Tell PostgREST to reload its schema cache so newly-added or removed
-- views surface immediately. No-op if no PostgREST is listening.
NOTIFY pgrst, 'reload schema';
