-- atlas-data/dbt/api_v1_generated.sql
-- AUTO-GENERATED by atlas-data/dbt/scripts/generate_api_v1.py — do not hand-edit.
-- Re-running ./regenerate-api-v1.sh after a dbt-model change is the source of truth.
--
-- Apply via ./apply-api-v1.sh AFTER `dbt run` — the wrappers reference
-- marts.mart_* tables which only exist after dbt has built them.
-- All statements are idempotent (CREATE OR REPLACE / IF NOT EXISTS / DROP IF EXISTS).
--
-- For design rationale see:
--   website/docs/ai-developer/plans/active/PLAN-004-postgrest-api-v1-wrapper.md
--
-- ROLLBACK: undeploy + purge UIS first (./uis undeploy postgrest --app atlas
-- + ./uis configure postgrest --app atlas --purge), then DROP SCHEMA api_v1 CASCADE.

CREATE SCHEMA IF NOT EXISTS api_v1;

-- activity_catalog  ←  marts.mart_activity_catalog
CREATE OR REPLACE VIEW api_v1.activity_catalog AS SELECT * FROM marts.mart_activity_catalog;
COMMENT ON COLUMN api_v1.activity_catalog.activity_id IS 'Composite slug (e.g. ''redcross-besokstjeneste''). Stable across
refreshes. Unique within this view.';
COMMENT ON COLUMN api_v1.activity_catalog.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO offering the activity.';
COMMENT ON COLUMN api_v1.activity_catalog.canonical_name IS 'Atlas''s canonical Norwegian name for the activity.';
COMMENT ON COLUMN api_v1.activity_catalog.service_category_code IS 'ICNPO-derived service category code (e.g. ''health'',
''social-services''). FK to ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.activity_catalog.service_category_label_no IS 'Human-readable Norwegian label for service_category_code,
joined from ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.activity_catalog.is_active IS 'Whether this activity is still offered by the NGO. Inactive
activities are kept so historical analysis can still resolve
activity_id values.';
COMMENT ON COLUMN api_v1.activity_catalog.chapter_count IS 'Count of distinct active chapters offering this activity. Zero
when the activity exists in dim_activity but no active chapter
provides it (rare but possible during transitions).';

-- coverage_gap_barnefattigdom  ←  marts.mart_coverage_gap_barnefattigdom
CREATE OR REPLACE VIEW api_v1.coverage_gap_barnefattigdom AS SELECT * FROM marts.mart_coverage_gap_barnefattigdom;
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner are included. Unique within this view.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.kommune_name IS 'Joined from fact_kommune_indicators (originally from dim_kommune).';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.fylke_name IS 'Joined from fact_kommune_indicators (originally from
dim_fylke). NULL for kommuner whose fylke_nr isn''t in
dim_fylke (rare — Svalbard 21xx).';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.year IS 'The latest year for ssb-08764/EUskala60. Same value across all
rows; carried on each row so the consumer reads it without a
separate query.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.value_pct IS 'EU-skala 60 % share — the percent of children under 18 in
low-income households (defined as < 60 % of national median
equivalised income). NULL when upstream suppressed the cell.';
COMMENT ON COLUMN api_v1.coverage_gap_barnefattigdom.personer IS 'Number of children under 18 in low-income households at the
same year. NULL when upstream suppressed the cell.';

-- distrikt_summary  ←  marts.mart_distrikt_summary
CREATE OR REPLACE VIEW api_v1.distrikt_summary AS SELECT * FROM marts.mart_distrikt_summary;
COMMENT ON COLUMN api_v1.distrikt_summary.chapter_id IS 'Composite slug for the regional chapter (e.g.
''redcross-oslo''). Stable across refreshes. Unique within this
view.';
COMMENT ON COLUMN api_v1.distrikt_summary.name IS 'Display name for the regional chapter (e.g. ''Oslo Røde Kors'').';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_nr IS '4-digit kommune code where the regional chapter is
headquartered. NULL for distrikter without a single HQ
kommune. Note: kommune_coverage_count tells you how many
*child* kommuner the distrikt covers — that''s the operational
footprint, not where the office sits.';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_name IS 'Joined from dim_kommune. NULL when kommune_nr is NULL.';
COMMENT ON COLUMN api_v1.distrikt_summary.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO this distrikt belongs to.';
COMMENT ON COLUMN api_v1.distrikt_summary.child_count IS 'Count of active local chapters whose parent_chapter_id equals
this distrikt''s chapter_id. The "lokalforeninger" total shown
in the UI.';
COMMENT ON COLUMN api_v1.distrikt_summary.kommune_coverage_count IS 'Count of distinct kommuner served by this distrikt''s active
children (kommune_nr IS NOT NULL). The operational footprint;
may be smaller than child_count when multiple children share
a kommune.';

-- indicator_latest_values  ←  marts.mart_indicator_latest_values
CREATE OR REPLACE VIEW api_v1.indicator_latest_values AS SELECT * FROM marts.mart_indicator_latest_values;
COMMENT ON COLUMN api_v1.indicator_latest_values.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''. Joins back to
fact_kommune_indicators.source_id.';
COMMENT ON COLUMN api_v1.indicator_latest_values.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde''). Combined with source_id and
kommune_nr forms the natural key of this view.';
COMMENT ON COLUMN api_v1.indicator_latest_values.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner are included.';
COMMENT ON COLUMN api_v1.indicator_latest_values.kommune_name IS 'Joined from fact_kommune_indicators (originally from dim_kommune).';
COMMENT ON COLUMN api_v1.indicator_latest_values.fylke_name IS 'Joined from fact_kommune_indicators (originally from
dim_fylke). NULL when the kommune''s fylke_nr isn''t present in
dim_fylke (rare — happens for codes like Svalbard 21xx).';
COMMENT ON COLUMN api_v1.indicator_latest_values.value IS 'Numeric value at latest_year. Unit depends on (source_id,
contents_code) — see the source''s README. NULL when upstream
suppressed the cell.';
COMMENT ON COLUMN api_v1.indicator_latest_values.status IS 'SSB suppression marker (e.g. '':'' for ''not available''). NULL
when value is present.';
COMMENT ON COLUMN api_v1.indicator_latest_values.year IS 'The latest year for this (source_id, contents_code). Repeats
across all kommuner for a given indicator — kept on the row so
PostgREST consumers can read it without a separate join.';

-- indicator_missing_kommuner  ←  marts.mart_indicator_missing_kommuner
CREATE OR REPLACE VIEW api_v1.indicator_missing_kommuner AS SELECT * FROM marts.mart_indicator_missing_kommuner;
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde'').';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.kommune_nr IS '4-digit zero-padded kommune code. FK to dim_kommune; only
active kommuner with no value at latest_year are listed.';
COMMENT ON COLUMN api_v1.indicator_missing_kommuner.kommune_name IS 'Joined from dim_kommune.';

-- indicator_summary  ←  marts.mart_indicator_summary
CREATE OR REPLACE VIEW api_v1.indicator_summary AS SELECT * FROM marts.mart_indicator_summary;
COMMENT ON COLUMN api_v1.indicator_summary.source_id IS 'Atlas source identifier, e.g. ''ssb-08764''. Joins back to
fact_kommune_indicators.source_id and to the source declarations
in indicators/sources.yml.';
COMMENT ON COLUMN api_v1.indicator_summary.contents_code IS 'Source-specific ContentsCode verbatim from upstream (e.g.
''EUskala60'', ''Folkemengde''). Combined with source_id forms the
natural key of this view.';
COMMENT ON COLUMN api_v1.indicator_summary.contents_label IS 'Human-readable label for contents_code, verbatim from upstream.
NULL only if every contributing row had a NULL label (rare).';
COMMENT ON COLUMN api_v1.indicator_summary.latest_year IS 'Most recent calendar year for which this (source_id,
contents_code) has any rows in fact_kommune_indicators. The
coverage and value-range columns below are computed against
this year only.';
COMMENT ON COLUMN api_v1.indicator_summary.kommuner_with_value IS 'Count of active kommuner (kommune_is_active = true) that have a
non-NULL value for this indicator at latest_year. The headline
coverage number on the data explorer.';
COMMENT ON COLUMN api_v1.indicator_summary.kommuner_with_null IS 'Count of active kommuner that have a row at latest_year but
value IS NULL (i.e. upstream suppressed the cell). Inactive
kommuner are not counted.';
COMMENT ON COLUMN api_v1.indicator_summary.min_value IS 'Minimum non-NULL value across all rows at latest_year, regardless
of whether the kommune is active. NULL if no row had a value.';
COMMENT ON COLUMN api_v1.indicator_summary.max_value IS 'Maximum non-NULL value across all rows at latest_year, regardless
of whether the kommune is active. NULL if no row had a value.';
COMMENT ON COLUMN api_v1.indicator_summary.upstream_updated IS 'Most recent fact_kommune_indicators.updated_at across the rows
that contributed to this summary. Useful for staleness checks
per indicator without joining to raw.*.';

-- kommune_local_chapters  ←  marts.mart_kommune_local_chapters
CREATE OR REPLACE VIEW api_v1.kommune_local_chapters AS SELECT * FROM marts.mart_kommune_local_chapters;
COMMENT ON COLUMN api_v1.kommune_local_chapters.kommune_nr IS '4-digit kommune code where the local chapter operates. FK to
dim_kommune. The primary filter dimension for this view.
Chapters with NULL kommune_nr are excluded by the view (this
isn''t "local chapters in a kommune" if there''s no kommune).
The relationships test is `warn`-severity because Svalbard
(2100) is a real Red Cross local chapter location whose
kommune code isn''t in dim_kommune.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.chapter_id IS 'Composite slug for the local chapter (e.g.
''redcross-oslo-grunerløkka''). Repeats across rows when the
chapter offers multiple service categories.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.name IS 'Display name for the local chapter.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_orgnr IS '9-digit Brreg organisasjonsnummer of the NGO that owns the chapter.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_name IS 'Joined from dim_ngo (legal name).';
COMMENT ON COLUMN api_v1.kommune_local_chapters.ngo_brand_name IS 'Joined from dim_ngo (brand name when distinct from legal
name). NULL when the NGO doesn''t use a brand alias.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.service_category_code IS 'ICNPO-derived service category code for one of the activities
this chapter offers. Combined with chapter_id forms the
natural key of this view (rows are unique on
(chapter_id, service_category_code)).';
COMMENT ON COLUMN api_v1.kommune_local_chapters.service_category_label_no IS 'Human-readable Norwegian label for service_category_code,
joined from ref_atlas_service_category.';
COMMENT ON COLUMN api_v1.kommune_local_chapters.sort_order IS 'Display order from ref_atlas_service_category. Used by the UI
to render service categories in a consistent sequence; carry
on the row so consumers can sort without a separate query.';

-- ngo_index  ←  marts.mart_ngo_index
CREATE OR REPLACE VIEW api_v1.ngo_index AS SELECT * FROM marts.mart_ngo_index;
COMMENT ON COLUMN api_v1.ngo_index.orgnr IS '9-digit Brreg organisasjonsnummer (text — leading zeros are
preserved). Natural key for this view.';
COMMENT ON COLUMN api_v1.ngo_index.slug IS 'kebab-case URL-friendly identifier (e.g. ''redcross'', ''kirkens-bymisjon'').';
COMMENT ON COLUMN api_v1.ngo_index.name IS 'Legal name from Brreg.';
COMMENT ON COLUMN api_v1.ngo_index.brand_name IS 'Common brand name when distinct from legal name (e.g.
''Sanitetskvinnene'' vs N.K.S.). NULL when the brand equals
the legal name.';
COMMENT ON COLUMN api_v1.ngo_index.website_url IS 'NGO''s primary website. Used as the outbound link from the index page.';
COMMENT ON COLUMN api_v1.ngo_index.tier IS 'Structural-fit tier (A / B / C) from
docs/research/ngo-landscape.md. v1 includes Tier A only.';
COMMENT ON COLUMN api_v1.ngo_index.chapter_data_shape IS 'How this NGO models its chapters. Values: ''distrikt+local''
(Red Cross), ''flat'' (single-tier), ''none'' (no chapters).
Drives which supply staging model the NGO uses.';
COMMENT ON COLUMN api_v1.ngo_index.has_chapters IS 'True when the NGO has any chapters at all (regardless of activity).';
COMMENT ON COLUMN api_v1.ngo_index.primary_focus IS 'One-line description of the NGO''s main mission area.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_1 IS 'ICNPO classification code (primary). See ref_icnpo. NULL when
unclassified.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_2 IS 'ICNPO classification code (secondary). NULL when not used.';
COMMENT ON COLUMN api_v1.ngo_index.icnpo_code_3 IS 'ICNPO classification code (tertiary). NULL when not used.';
COMMENT ON COLUMN api_v1.ngo_index.chapter_count IS 'Count of active chapters for this NGO (filtered by
dim_chapter.is_active = true). Zero if the NGO has no chapters
or all chapters are dormant.';
COMMENT ON COLUMN api_v1.ngo_index.has_supply IS 'Convenience boolean: chapter_count > 0. True when the NGO has
at least one active chapter — i.e. it appears on the supply
side of Atlas.';

-- ngo_overview  ←  marts.mart_ngo_overview
CREATE OR REPLACE VIEW api_v1.ngo_overview AS SELECT * FROM marts.mart_ngo_overview;
COMMENT ON COLUMN api_v1.ngo_overview.orgnr IS '9-digit Brreg organisasjonsnummer. Natural key for this view.';
COMMENT ON COLUMN api_v1.ngo_overview.chapter_count IS 'Total count of chapters for this NGO across all levels (active + inactive).';
COMMENT ON COLUMN api_v1.ngo_overview.national_count IS 'Count of chapters at chapter_level = ''national''.';
COMMENT ON COLUMN api_v1.ngo_overview.regional_count IS 'Count of chapters at chapter_level = ''regional'' (e.g. Red Cross distrikt).';
COMMENT ON COLUMN api_v1.ngo_overview.local_count IS 'Count of chapters at chapter_level = ''local'' (the kommune-bound branches).';
COMMENT ON COLUMN api_v1.ngo_overview.activity_count IS 'Count of distinct activities offered by this NGO (rows in
dim_activity for this orgnr).';
COMMENT ON COLUMN api_v1.ngo_overview.kommune_count IS 'Count of distinct kommuner with at least one active local
chapter for this NGO. The "footprint" metric for coverage-gap
questions.';

-- Grant SELECT to the per-app anon role if it exists (created by UIS's
-- ./uis configure postgrest --app atlas). Guarded so this migration
-- applies cleanly against environments where UIS hasn't run configure yet.
DO $$ BEGIN
  IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'atlas_web_anon') THEN
    GRANT USAGE ON SCHEMA api_v1 TO atlas_web_anon;
    GRANT SELECT ON ALL TABLES IN SCHEMA api_v1 TO atlas_web_anon;
    ALTER DEFAULT PRIVILEGES IN SCHEMA api_v1
      GRANT SELECT ON TABLES TO atlas_web_anon;
  END IF;
END $$;

-- Tell PostgREST to reload its schema cache so newly-added or removed
-- views surface immediately. No-op if no PostgREST is listening.
NOTIFY pgrst, 'reload schema';
