#!/usr/bin/env bash
# _sources_manifest.csv and _sources_dimensions.csv are GENERATED by
# scripts/build_sources_seed.py from ingest/src/sources/*/manifest.yml, and
# both are committed. This re-runs the generator into a temp directory and
# diffs. A difference means someone edited a manifest and did not regenerate.
#
# 🔴 WHY THIS EXISTS. On 2026-09-22 atlas#416 repointed fhi-innvkat from FHI
# table 650 (deleted upstream, 404) to 932. It updated manifest.yml and NOT
# this seed. The transform then loaded the stale seed faithfully, and
# api_v1.meta_sources published:
#
#     upstream_id   650
#     upstream_url  .../nokkel/table/650   -> 404 from FHI
#
# for data that had been correctly fetched from 932. ⚠️ THE DATA WAS RIGHT AND
# THE CATALOGUE LIED ABOUT WHERE IT CAME FROM — a consumer following
# upstream_url to check provenance, which is the entire purpose of that field,
# got a 404 and no way to tell the figures themselves were fine. Nothing
# failed. A correct pipeline published a stale input (urb-agents #1407).
#
# 🔵 meta_sources IS BUILT FROM THIS CSV, NOT FROM THE MANIFESTS. That is the
# whole trap: the manifest is the human-authored truth, the seed is what
# actually reaches consumers, and until now nothing compared them.
#
# 🔵 THE SIBLINGS ALREADY HAD THIS AND THIS ONE DID NOT. Of the three
# generators under scripts/, generate_api_v1.py is drift-gated by
# check-api-v1.sh and extract_lineage.py by check-lineage-is-current.sh.
# build_sources_seed.py was the only one without — while two other checks
# (check-source-ids-are-real, check-every-source-is-served) READ its output
# and trusted it. ops-dev asked whether siblings existed; they did, and this
# was the gap.
set -euo pipefail
cd "$(dirname "$0")"

PY=./.venv/bin/python
[ -x "$PY" ] || PY=python3

SEED_DIR=seeds/sources
for f in _sources_manifest.csv _sources_dimensions.csv; do
  [ -f "$SEED_DIR/$f" ] || { echo "✗ CANNOT CHECK: $SEED_DIR/$f is missing." >&2; exit 2; }
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! "$PY" scripts/build_sources_seed.py \
      --out "$TMP/_sources_manifest.csv" \
      --dimensions-out "$TMP/_sources_dimensions.csv" >/dev/null 2>"$TMP/err"; then
  echo "✗ CANNOT CHECK: build_sources_seed.py failed — the check refuses rather" >&2
  echo "  than passing on having compared nothing." >&2
  sed 's/^/    /' "$TMP/err" >&2
  exit 2
fi

# 🔴 The generator must actually have produced something. A zero-byte or
# header-only output would diff clean against a committed file only if that
# were also empty, but an empty regeneration is a broken generator, not a
# clean bill of health.
rows=$(($(wc -l < "$TMP/_sources_manifest.csv") - 1))
if [ "$rows" -lt 1 ]; then
  echo "✗ CANNOT CHECK: the generator emitted $rows source rows." >&2
  exit 2
fi

drift=0
for f in _sources_manifest.csv _sources_dimensions.csv; do
  if ! diff -q "$SEED_DIR/$f" "$TMP/$f" >/dev/null 2>&1; then
    echo "✗ $SEED_DIR/$f is not what build_sources_seed.py produces today:"
    diff -u "$SEED_DIR/$f" "$TMP/$f" | grep -E '^[+-][^+-]' | head -12 | sed 's/^/    /' | cut -c1-140
    drift=1
  fi
done

if [ "$drift" -ne 0 ]; then
  echo
  echo "  A manifest.yml changed and the seed was not regenerated. meta_sources is"
  echo "  built from the SEED, so the catalogue would publish the old values."
  echo "  Fix: cd atlas-data/dbt && ./.venv/bin/python scripts/build_sources_seed.py"
  echo "       then commit seeds/sources/_sources_*.csv"
  exit 1
fi

echo "  ✓ the committed sources seeds match what build_sources_seed.py produces ($rows sources)"
