import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    // The homepage lives at src/pages/index.tsx (a React page), not as a
    // doc — so this sidebar starts with the About category. Visitors who
    // click "Docs" in the navbar land on the first About doc.
    {
      type: 'category',
      label: 'About',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'about' }],
    },
    {
      type: 'category',
      label: 'Sector',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'sector' }],
    },
    {
      type: 'category',
      label: 'Getting started',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index', description: 'In progress — one page per canonical entity.' },
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Measurements',
      link: { type: 'generated-index', description: 'In progress — one page per (source_id, contents_code) pair.' },
      items: [{ type: 'autogenerated', dirName: 'measurements' }],
    },
    {
      // Datasets catalogue — landings only, NOT autogenerated. The catalogue
      // is generated via `npm run sources:generate` into docs/datasets/*.mdx,
      // docs/topics/*.mdx, docs/publishers/*.mdx. Per-dataset pages are
      // reached via the landings (front page topic grid, topic index,
      // publisher brand pages). PLAN-002 + PLAN-catalog-vocabulary.
      type: 'category',
      label: 'Datasets',
      link: { type: 'doc', id: 'datasets/index' },
      items: [
        {
          type: 'category',
          label: 'Collections',
          collapsed: true,
          items: [
            'datasets/collections/grant-application-essentials',
          ],
        },
        {
          type: 'category',
          label: 'By topic',
          collapsed: true,
          items: [
            'topics/health',
            'topics/demographics',
            'topics/income',
            'topics/education',
            'topics/social',
            'topics/ngo-supply',
            'topics/reference',
          ],
        },
        {
          type: 'category',
          label: 'By publisher',
          collapsed: true,
          items: [
            'publishers/ssb',
            'publishers/fhi',
            'publishers/bufdir',
            'publishers/redcross',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      link: { type: 'doc', id: 'developers/index' },
      items: [{ type: 'autogenerated', dirName: 'developers' }],
    },
    {
      type: 'category',
      label: 'Contributors',
      link: { type: 'doc', id: 'contributors/index' },
      items: [{ type: 'autogenerated', dirName: 'contributors' }],
    },
    {
      type: 'category',
      label: 'AI developer',
      link: { type: 'generated-index', description: 'Implementation plans, agent workflow, planning conventions.' },
      items: [{ type: 'autogenerated', dirName: 'ai-developer' }],
    },
  ],
};

export default sidebars;
