import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'About',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'about' }],
    },
    {
      type: 'category',
      label: 'Sector',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'sector' }],
    },
    {
      type: 'category',
      label: 'Getting started',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index', description: 'In progress — one page per canonical entity.' },
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Measurements',
      link: { type: 'generated-index', description: 'In progress — one page per (source_id, contents_code) pair.' },
      items: [{ type: 'autogenerated', dirName: 'measurements' }],
    },
    {
      type: 'category',
      label: 'Sources',
      link: { type: 'generated-index', description: 'In progress — one page per ingest source.' },
      items: [{ type: 'autogenerated', dirName: 'sources' }],
    },
    {
      type: 'category',
      label: 'Developers',
      link: { type: 'doc', id: 'developers/index' },
      items: [{ type: 'autogenerated', dirName: 'developers' }],
    },
    {
      type: 'category',
      label: 'Contributors',
      link: { type: 'doc', id: 'contributors/index' },
      items: [{ type: 'autogenerated', dirName: 'contributors' }],
    },
    {
      type: 'category',
      label: 'AI developer',
      link: { type: 'generated-index', description: 'Implementation plans, agent workflow, planning conventions.' },
      items: [{ type: 'autogenerated', dirName: 'ai-developer' }],
    },
  ],
};

export default sidebars;
