import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'About',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'about' }],
    },
    {
      type: 'category',
      label: 'Sector',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'sector' }],
    },
    {
      type: 'category',
      label: 'Getting started',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index', description: 'In progress — one page per canonical entity.' },
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Measurements',
      link: { type: 'generated-index', description: 'In progress — one page per (source_id, contents_code) pair.' },
      items: [{ type: 'autogenerated', dirName: 'measurements' }],
    },
    {
      // Sources catalogue — landings only, NOT autogenerated. The catalogue
      // is generated via `npm run sources:generate` into docs/sources/*.mdx,
      // which would inflate the sidebar with 41+ source pages if
      // autogenerated. Per-source pages are reached via the landings
      // (front page category grid, browse, category index, publisher
      // brand pages). PLAN-002 + PLAN-003.
      type: 'category',
      label: 'Sources',
      link: { type: 'doc', id: 'sources/index' },
      items: [
        'sources/browse',
        {
          type: 'category',
          label: 'By category',
          collapsed: true,
          items: [
            'sources/category/health',
            'sources/category/demographics',
            'sources/category/income',
            'sources/category/education',
            'sources/category/social',
            'sources/category/ngo-supply',
            'sources/category/reference',
          ],
        },
        {
          type: 'category',
          label: 'By publisher',
          collapsed: true,
          items: [
            'sources/by/ssb',
            'sources/by/fhi',
            'sources/by/bufdir',
            'sources/by/redcross',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      link: { type: 'doc', id: 'developers/index' },
      items: [{ type: 'autogenerated', dirName: 'developers' }],
    },
    {
      type: 'category',
      label: 'Contributors',
      link: { type: 'doc', id: 'contributors/index' },
      items: [{ type: 'autogenerated', dirName: 'contributors' }],
    },
    {
      type: 'category',
      label: 'AI developer',
      link: { type: 'generated-index', description: 'Implementation plans, agent workflow, planning conventions.' },
      items: [{ type: 'autogenerated', dirName: 'ai-developer' }],
    },
  ],
};

export default sidebars;
